"""Item bank for PRICE CHECK — {prompt, emoji, answer, money, unit, fact, category}."""

ITEMS = [
    # ---------------- grocery ----------------
    {
        "prompt": "A dozen large eggs at the grocery store",
        "emoji": "🥚",
        "answer": 3.49,
        "money": True,
        "unit": "",
        "fact": "A dozen eggs runs about $3.50 — and one hen lays roughly 300 eggs a year.",
        "category": "grocery",
    },
    {
        "prompt": "A gallon of whole milk",
        "emoji": "🥛",
        "answer": 3.99,
        "money": True,
        "unit": "",
        "fact": "A gallon of milk is about $4 and weighs almost 8.6 pounds.",
        "category": "grocery",
    },
    {
        "prompt": "A loaf of white sandwich bread",
        "emoji": "🍞",
        "answer": 2.99,
        "money": True,
        "unit": "",
        "fact": "A basic loaf costs about $3 and holds roughly 20 slices.",
        "category": "grocery",
    },
    {
        "prompt": "A McDonald's Big Mac",
        "emoji": "🍔",
        "answer": 5.99,
        "money": True,
        "unit": "",
        "fact": "A Big Mac is about $6 in the US — its price is used to compare money worldwide.",
        "category": "grocery",
    },
    {
        "prompt": "A McDonald's plain hamburger",
        "emoji": "🍔",
        "answer": 2.49,
        "money": True,
        "unit": "",
        "fact": "The plain hamburger is about $2.50 — one of the cheapest things on the menu.",
        "category": "grocery",
    },
    {
        "prompt": "A gumball from a gumball machine",
        "emoji": "🔴",
        "answer": 0.25,
        "money": True,
        "unit": "",
        "fact": "A gumball is usually a quarter — but old machines once charged just a penny!",
        "category": "grocery",
    },
    {
        "prompt": "A first-class US postage stamp (Forever stamp)",
        "emoji": "📮",
        "answer": 0.73,
        "money": True,
        "unit": "",
        "fact": "A Forever stamp is about 73 cents and still works even after prices rise.",
        "category": "grocery",
    },
    {
        "prompt": "A gallon of gasoline (US average)",
        "emoji": "⛽",
        "answer": 3.49,
        "money": True,
        "unit": "",
        "fact": "US gas averages around $3.50 a gallon, though it changes week to week.",
        "category": "grocery",
    },
    {
        "prompt": "A movie theater ticket (US average)",
        "emoji": "🎟️",
        "answer": 12,
        "money": True,
        "unit": "",
        "fact": "The average movie ticket is about $12 — back in 1970 it was under a dollar!",
        "category": "grocery",
    },
    {
        "prompt": "A candy bar at the checkout",
        "emoji": "🍫",
        "answer": 1.99,
        "money": True,
        "unit": "",
        "fact": "A candy bar is about $2 today — it was a nickel a hundred years ago.",
        "category": "grocery",
    },
    {
        "prompt": "A can of soda from a vending machine",
        "emoji": "🥤",
        "answer": 1.75,
        "money": True,
        "unit": "",
        "fact": "A vending-machine soda is about $1.75 — pricier than a can from a 12-pack.",
        "category": "grocery",
    },
    {
        "prompt": "A dozen glazed doughnuts",
        "emoji": "🍩",
        "answer": 11.99,
        "money": True,
        "unit": "",
        "fact": "A dozen doughnuts costs about $12 — cheaper by the dozen than one at a time.",
        "category": "grocery",
    },
    {
        "prompt": "A single scoop of ice cream at a shop",
        "emoji": "🍦",
        "answer": 4.49,
        "money": True,
        "unit": "",
        "fact": "One scoop is about $4.50 — Americans eat around 4 gallons of ice cream a year each.",
        "category": "grocery",
    },
    {
        "prompt": "Calories in a medium banana",
        "emoji": "🍌",
        "answer": 105,
        "money": False,
        "unit": "calories",
        "fact": "A banana has about 105 calories and more potassium than most fruits.",
        "category": "grocery",
    },
    {
        "prompt": "Slices in a typical large pizza",
        "emoji": "🍕",
        "answer": 8,
        "money": False,
        "unit": "slices",
        "fact": "A large pizza is usually cut into 8 slices — sometimes 10 at a pizzeria.",
        "category": "grocery",
    },
    {
        "prompt": "Calories in a can of regular cola",
        "emoji": "🥤",
        "answer": 140,
        "money": False,
        "unit": "calories",
        "fact": "A can of cola has about 140 calories, almost all from sugar.",
        "category": "grocery",
    },

    # ---------------- stuff ----------------
    {
        "prompt": "Keys on a standard piano",
        "emoji": "🎹",
        "answer": 88,
        "money": False,
        "unit": "keys",
        "fact": "A piano has 88 keys — 52 white and 36 black.",
        "category": "stuff",
    },
    {
        "prompt": "Strings on a standard guitar",
        "emoji": "🎸",
        "answer": 6,
        "money": False,
        "unit": "strings",
        "fact": "A standard guitar has 6 strings, though 12-string guitars exist too.",
        "category": "stuff",
    },
    {
        "prompt": "Squares on a chessboard",
        "emoji": "♟️",
        "answer": 64,
        "money": False,
        "unit": "squares",
        "fact": "A chessboard has 64 squares in an 8-by-8 grid.",
        "category": "stuff",
    },
    {
        "prompt": "Cards in a standard deck (no jokers)",
        "emoji": "🃏",
        "answer": 52,
        "money": False,
        "unit": "cards",
        "fact": "A deck has 52 cards — one for each week of the year.",
        "category": "stuff",
    },
    {
        "prompt": "Crayons in the classic big Crayola box",
        "emoji": "🖍️",
        "answer": 64,
        "money": False,
        "unit": "crayons",
        "fact": "The famous big Crayola box holds 64 crayons and has a built-in sharpener.",
        "category": "stuff",
    },
    {
        "prompt": "Holes on a standard golf course",
        "emoji": "⛳",
        "answer": 18,
        "money": False,
        "unit": "holes",
        "fact": "A full golf course has 18 holes — a round can cover several miles of walking.",
        "category": "stuff",
    },
    {
        "prompt": "Pins set up in ten-pin bowling",
        "emoji": "🎳",
        "answer": 10,
        "money": False,
        "unit": "pins",
        "fact": "Bowling uses 10 pins in a triangle — knock them all down for a strike.",
        "category": "stuff",
    },
    {
        "prompt": "Sides on a stop sign",
        "emoji": "🛑",
        "answer": 8,
        "money": False,
        "unit": "sides",
        "fact": "A stop sign is an octagon with 8 sides — the shape means STOP even if snow covers the word.",
        "category": "stuff",
    },
    {
        "prompt": "Pockets on a pool (billiards) table",
        "emoji": "🎱",
        "answer": 6,
        "money": False,
        "unit": "pockets",
        "fact": "A pool table has 6 pockets — four corners and two in the middle.",
        "category": "stuff",
    },
    {
        "prompt": "Inches in one foot",
        "emoji": "📏",
        "answer": 12,
        "money": False,
        "unit": "inches",
        "fact": "There are 12 inches in a foot — the ruler on your desk proves it.",
        "category": "stuff",
    },
    {
        "prompt": "Feet in one mile",
        "emoji": "🛣️",
        "answer": 5280,
        "money": False,
        "unit": "feet",
        "fact": "A mile is 5,280 feet — an oddly specific number from old Roman measurements.",
        "category": "stuff",
    },
    {
        "prompt": "Height of a basketball hoop from the floor",
        "emoji": "🏀",
        "answer": 10,
        "money": False,
        "unit": "feet",
        "fact": "The rim is exactly 10 feet high — the same height since the game was invented in 1891.",
        "category": "stuff",
    },
    {
        "prompt": "Total pips (dots) on a six-sided die",
        "emoji": "🎲",
        "answer": 21,
        "money": False,
        "unit": "pips",
        "fact": "Add the faces 1 through 6 and a die has 21 dots in all.",
        "category": "stuff",
    },
    {
        "prompt": "Small cubes in a 3x3 Rubik's Cube",
        "emoji": "🧩",
        "answer": 27,
        "money": False,
        "unit": "cubes",
        "fact": "A Rubik's Cube is made of 27 little cubes — but the center one you never see.",
        "category": "stuff",
    },
    {
        "prompt": "Letters in the English alphabet",
        "emoji": "🔤",
        "answer": 26,
        "money": False,
        "unit": "letters",
        "fact": "The alphabet has 26 letters — the sentence 'The quick brown fox...' uses every one.",
        "category": "stuff",
    },
    {
        "prompt": "Length of an American football field (with end zones)",
        "emoji": "🏈",
        "answer": 120,
        "money": False,
        "unit": "yards",
        "fact": "With both end zones a football field is 120 yards long — 100 for play, 10 each end.",
        "category": "stuff",
    },

    # ---------------- body ----------------
    {
        "prompt": "Bones in the adult human body",
        "emoji": "🦴",
        "answer": 206,
        "money": False,
        "unit": "bones",
        "fact": "Adults have 206 bones — more than half of them are in the hands and feet.",
        "category": "body",
    },
    {
        "prompt": "Bones a baby is born with",
        "emoji": "👶",
        "answer": 300,
        "money": False,
        "unit": "bones",
        "fact": "Babies start with about 300 bones; many fuse together as they grow.",
        "category": "body",
    },
    {
        "prompt": "Teeth in a full set of adult teeth",
        "emoji": "🦷",
        "answer": 32,
        "money": False,
        "unit": "teeth",
        "fact": "Adults have 32 teeth, including 4 wisdom teeth in the back.",
        "category": "body",
    },
    {
        "prompt": "Baby teeth a young child has",
        "emoji": "🦷",
        "answer": 20,
        "money": False,
        "unit": "teeth",
        "fact": "Kids grow 20 baby teeth before the adult set pushes them out.",
        "category": "body",
    },
    {
        "prompt": "Chambers in the human heart",
        "emoji": "❤️",
        "answer": 4,
        "money": False,
        "unit": "chambers",
        "fact": "The heart has 4 chambers — two on top, two on the bottom, pumping in sync.",
        "category": "body",
    },
    {
        "prompt": "Pairs of ribs in the human body",
        "emoji": "🫁",
        "answer": 12,
        "money": False,
        "unit": "pairs",
        "fact": "Everyone has 12 pairs of ribs — that's 24 ribs protecting your lungs and heart.",
        "category": "body",
    },
    {
        "prompt": "Bones in one human hand",
        "emoji": "✋",
        "answer": 27,
        "money": False,
        "unit": "bones",
        "fact": "One hand has 27 bones, which is why it can make so many delicate movements.",
        "category": "body",
    },
    {
        "prompt": "Bones in one human foot",
        "emoji": "🦶",
        "answer": 26,
        "money": False,
        "unit": "bones",
        "fact": "Each foot has 26 bones — together your feet hold a quarter of all your bones.",
        "category": "body",
    },
    {
        "prompt": "Resting heartbeats per minute (adult)",
        "emoji": "💓",
        "answer": 70,
        "money": False,
        "unit": "beats",
        "fact": "A resting adult heart beats about 70 times a minute — over 100,000 times a day.",
        "category": "body",
    },
    {
        "prompt": "Muscles in the human body",
        "emoji": "💪",
        "answer": 600,
        "money": False,
        "unit": "muscles",
        "fact": "The body has about 600 muscles — even smiling uses more than a dozen.",
        "category": "body",
    },
    {
        "prompt": "Vertebrae in the human spine",
        "emoji": "🦴",
        "answer": 33,
        "money": False,
        "unit": "vertebrae",
        "fact": "The spine has 33 vertebrae stacked like building blocks down your back.",
        "category": "body",
    },
    {
        "prompt": "Percent of the human body that is water",
        "emoji": "💧",
        "answer": 60,
        "money": False,
        "unit": "percent",
        "fact": "About 60% of your body is water — that's why staying hydrated matters.",
        "category": "body",
    },
    {
        "prompt": "Chromosomes in a human cell",
        "emoji": "🧬",
        "answer": 46,
        "money": False,
        "unit": "chromosomes",
        "fact": "Human cells carry 46 chromosomes — 23 from each parent.",
        "category": "body",
    },
    {
        "prompt": "Length of the human small intestine",
        "emoji": "🌀",
        "answer": 20,
        "money": False,
        "unit": "feet",
        "fact": "The small intestine is about 20 feet long, coiled up inside your belly.",
        "category": "body",
    },
    {
        "prompt": "Bones in the human skull",
        "emoji": "💀",
        "answer": 22,
        "money": False,
        "unit": "bones",
        "fact": "The skull is made of 22 bones — only the jaw can actually move.",
        "category": "body",
    },
    {
        "prompt": "Liters of blood in an adult body",
        "emoji": "🩸",
        "answer": 5,
        "money": False,
        "unit": "liters",
        "fact": "An adult has about 5 liters of blood, which circles the whole body in under a minute.",
        "category": "body",
    },

    # ---------------- world ----------------
    {
        "prompt": "States in the United States",
        "emoji": "🇺🇸",
        "answer": 50,
        "money": False,
        "unit": "states",
        "fact": "The US has 50 states — the newest, Hawaii, joined in 1959.",
        "category": "world",
    },
    {
        "prompt": "Height of the Statue of Liberty (torch to base)",
        "emoji": "🗽",
        "answer": 151,
        "money": False,
        "unit": "feet",
        "fact": "Lady Liberty stands about 151 feet from base to torch — 305 feet counting the pedestal.",
        "category": "world",
    },
    {
        "prompt": "Height of Mount Everest",
        "emoji": "🏔️",
        "answer": 29032,
        "money": False,
        "unit": "feet",
        "fact": "Everest tops out at 29,032 feet — the highest point on Earth's surface.",
        "category": "world",
    },
    {
        "prompt": "Continents on Earth",
        "emoji": "🌍",
        "answer": 7,
        "money": False,
        "unit": "continents",
        "fact": "There are 7 continents — Asia is the biggest and Australia the smallest.",
        "category": "world",
    },
    {
        "prompt": "Oceans on Earth",
        "emoji": "🌊",
        "answer": 5,
        "money": False,
        "unit": "oceans",
        "fact": "Earth has 5 oceans — the Pacific alone is bigger than all the land combined.",
        "category": "world",
    },
    {
        "prompt": "Time zones around the world",
        "emoji": "🕰️",
        "answer": 24,
        "money": False,
        "unit": "zones",
        "fact": "The world is split into 24 main time zones, one for each hour of the day.",
        "category": "world",
    },
    {
        "prompt": "Countries in the world",
        "emoji": "🗺️",
        "answer": 195,
        "money": False,
        "unit": "countries",
        "fact": "Most people count 195 countries — the UN officially recognizes 193 of them.",
        "category": "world",
    },
    {
        "prompt": "Wonders of the ancient world",
        "emoji": "🏛️",
        "answer": 7,
        "money": False,
        "unit": "wonders",
        "fact": "There were 7 ancient wonders — only the Great Pyramid still stands today.",
        "category": "world",
    },
    {
        "prompt": "Stars on the US flag",
        "emoji": "⭐",
        "answer": 50,
        "money": False,
        "unit": "stars",
        "fact": "The flag has 50 stars, one for each state, arranged in neat rows.",
        "category": "world",
    },
    {
        "prompt": "Stripes on the US flag",
        "emoji": "🇺🇸",
        "answer": 13,
        "money": False,
        "unit": "stripes",
        "fact": "The flag has 13 stripes for the 13 original colonies.",
        "category": "world",
    },
    {
        "prompt": "Original American colonies",
        "emoji": "📜",
        "answer": 13,
        "money": False,
        "unit": "colonies",
        "fact": "The country began as 13 colonies along the Atlantic coast.",
        "category": "world",
    },
    {
        "prompt": "The Great Lakes in North America",
        "emoji": "🏞️",
        "answer": 5,
        "money": False,
        "unit": "lakes",
        "fact": "There are 5 Great Lakes — spell HOMES for Huron, Ontario, Michigan, Erie, Superior.",
        "category": "world",
    },
    {
        "prompt": "Floors in the Empire State Building",
        "emoji": "🏙️",
        "answer": 102,
        "money": False,
        "unit": "floors",
        "fact": "The Empire State Building has 102 floors and once was the tallest in the world.",
        "category": "world",
    },
    {
        "prompt": "Height of the Eiffel Tower",
        "emoji": "🗼",
        "answer": 1083,
        "money": False,
        "unit": "feet",
        "fact": "The Eiffel Tower is about 1,083 feet tall and grows a few inches in summer heat.",
        "category": "world",
    },
    {
        "prompt": "Length of the Great Wall of China",
        "emoji": "🧱",
        "answer": 13000,
        "money": False,
        "unit": "miles",
        "fact": "The Great Wall stretches more than 13,000 miles across northern China.",
        "category": "world",
    },
    {
        "prompt": "Sides on the Pentagon building",
        "emoji": "⬟",
        "answer": 5,
        "money": False,
        "unit": "sides",
        "fact": "The Pentagon has 5 sides — and it's named after that shape.",
        "category": "world",
    },

    # ---------------- space ----------------
    {
        "prompt": "Planets in our solar system",
        "emoji": "🪐",
        "answer": 8,
        "money": False,
        "unit": "planets",
        "fact": "There are 8 planets since Pluto was reclassified as a dwarf planet in 2006.",
        "category": "space",
    },
    {
        "prompt": "Moons orbiting the Earth",
        "emoji": "🌙",
        "answer": 1,
        "money": False,
        "unit": "moon",
        "fact": "Earth has just 1 moon — big enough to cause the ocean tides.",
        "category": "space",
    },
    {
        "prompt": "Moons orbiting Mars",
        "emoji": "🔴",
        "answer": 2,
        "money": False,
        "unit": "moons",
        "fact": "Mars has 2 tiny moons, Phobos and Deimos, shaped more like potatoes than spheres.",
        "category": "space",
    },
    {
        "prompt": "Minutes for sunlight to reach Earth",
        "emoji": "☀️",
        "answer": 8,
        "money": False,
        "unit": "minutes",
        "fact": "Sunlight takes about 8 minutes to reach us — you always see the Sun as it was.",
        "category": "space",
    },
    {
        "prompt": "Days for the Moon to orbit the Earth",
        "emoji": "🌗",
        "answer": 27,
        "money": False,
        "unit": "days",
        "fact": "The Moon circles Earth in about 27 days — close to one month.",
        "category": "space",
    },
    {
        "prompt": "Days in an Earth year",
        "emoji": "📅",
        "answer": 365,
        "money": False,
        "unit": "days",
        "fact": "A year is 365 days — the extra quarter-day gives us a leap year every four.",
        "category": "space",
    },
    {
        "prompt": "Age of the universe",
        "emoji": "🌌",
        "answer": 13800000000,
        "money": False,
        "unit": "years",
        "fact": "The universe is about 13.8 billion years old — that's a lot of birthday candles.",
        "category": "space",
    },
    {
        "prompt": "Distance from the Earth to the Moon",
        "emoji": "🌕",
        "answer": 239000,
        "money": False,
        "unit": "miles",
        "fact": "The Moon sits about 239,000 miles away — you could line up 30 Earths in the gap.",
        "category": "space",
    },
    {
        "prompt": "Distance from the Earth to the Sun",
        "emoji": "☀️",
        "answer": 93000000,
        "money": False,
        "unit": "miles",
        "fact": "The Sun is about 93 million miles away — this distance is called an astronomical unit.",
        "category": "space",
    },
    {
        "prompt": "Speed of light",
        "emoji": "💡",
        "answer": 186000,
        "money": False,
        "unit": "mi/s",
        "fact": "Light zips along at about 186,000 miles per second — nothing goes faster.",
        "category": "space",
    },
    {
        "prompt": "Astronauts who have walked on the Moon",
        "emoji": "👨‍🚀",
        "answer": 12,
        "money": False,
        "unit": "astronauts",
        "fact": "Only 12 people have ever walked on the Moon, all between 1969 and 1972.",
        "category": "space",
    },
    {
        "prompt": "Official constellations in the sky",
        "emoji": "✨",
        "answer": 88,
        "money": False,
        "unit": "constellations",
        "fact": "Astronomers map the sky into 88 constellations, from Orion to the Big Dipper's Ursa Major.",
        "category": "space",
    },
    {
        "prompt": "Diameter of the Earth",
        "emoji": "🌐",
        "answer": 7918,
        "money": False,
        "unit": "miles",
        "fact": "Earth is about 7,900 miles across — it bulges slightly wider at the equator.",
        "category": "space",
    },
    {
        "prompt": "Earths that could fit inside the Sun",
        "emoji": "🌞",
        "answer": 1300000,
        "money": False,
        "unit": "Earths",
        "fact": "About 1.3 million Earths could fit inside the Sun — it's truly enormous.",
        "category": "space",
    },
    {
        "prompt": "Planets in our solar system that have rings",
        "emoji": "🪐",
        "answer": 4,
        "money": False,
        "unit": "planets",
        "fact": "Four planets have rings — Saturn's are the showiest, but Jupiter, Uranus and Neptune have them too.",
        "category": "space",
    },
    {
        "prompt": "Apollo missions that landed people on the Moon",
        "emoji": "🚀",
        "answer": 6,
        "money": False,
        "unit": "missions",
        "fact": "Six Apollo missions landed on the Moon, starting with Apollo 11 in 1969.",
        "category": "space",
    },

    # ---------------- animals ----------------
    {
        "prompt": "Legs on a spider",
        "emoji": "🕷️",
        "answer": 8,
        "money": False,
        "unit": "legs",
        "fact": "Spiders have 8 legs — that's how you tell them from 6-legged insects.",
        "category": "animals",
    },
    {
        "prompt": "Legs on an insect",
        "emoji": "🐜",
        "answer": 6,
        "money": False,
        "unit": "legs",
        "fact": "All insects have 6 legs — ants, bees, and beetles included.",
        "category": "animals",
    },
    {
        "prompt": "Hearts an octopus has",
        "emoji": "🐙",
        "answer": 3,
        "money": False,
        "unit": "hearts",
        "fact": "An octopus has 3 hearts and blue blood to go with them.",
        "category": "animals",
    },
    {
        "prompt": "Humps on a Bactrian camel",
        "emoji": "🐫",
        "answer": 2,
        "money": False,
        "unit": "humps",
        "fact": "A Bactrian camel has 2 humps; the Arabian dromedary has just one.",
        "category": "animals",
    },
    {
        "prompt": "Top speed of a cheetah",
        "emoji": "🐆",
        "answer": 70,
        "money": False,
        "unit": "mph",
        "fact": "A cheetah can hit about 70 mph — the fastest land animal alive.",
        "category": "animals",
    },
    {
        "prompt": "Top speed of a house cat",
        "emoji": "🐈",
        "answer": 30,
        "money": False,
        "unit": "mph",
        "fact": "A house cat can sprint about 30 mph — faster than the fastest human runner.",
        "category": "animals",
    },
    {
        "prompt": "Top diving speed of a peregrine falcon",
        "emoji": "🦅",
        "answer": 240,
        "money": False,
        "unit": "mph",
        "fact": "A peregrine falcon dives at about 240 mph — the fastest animal on Earth.",
        "category": "animals",
    },
    {
        "prompt": "Stomach compartments in a cow",
        "emoji": "🐄",
        "answer": 4,
        "money": False,
        "unit": "compartments",
        "fact": "A cow's stomach has 4 compartments to break down all that grass.",
        "category": "animals",
    },
    {
        "prompt": "Length of a blue whale",
        "emoji": "🐋",
        "answer": 100,
        "money": False,
        "unit": "feet",
        "fact": "A blue whale can reach about 100 feet — the largest animal ever to live.",
        "category": "animals",
    },
    {
        "prompt": "Legs on a lobster",
        "emoji": "🦞",
        "answer": 10,
        "money": False,
        "unit": "legs",
        "fact": "A lobster has 10 legs, and the front pair are its big claws.",
        "category": "animals",
    },
    {
        "prompt": "Bones in a giraffe's neck",
        "emoji": "🦒",
        "answer": 7,
        "money": False,
        "unit": "bones",
        "fact": "A giraffe's neck has just 7 bones — the very same number as yours.",
        "category": "animals",
    },
    {
        "prompt": "Height of an adult giraffe",
        "emoji": "🦒",
        "answer": 18,
        "money": False,
        "unit": "feet",
        "fact": "A grown giraffe stands about 18 feet tall — the tallest animal on land.",
        "category": "animals",
    },
    {
        "prompt": "Length of an elephant's pregnancy",
        "emoji": "🐘",
        "answer": 22,
        "money": False,
        "unit": "months",
        "fact": "Elephants are pregnant about 22 months — the longest of any land animal.",
        "category": "animals",
    },
    {
        "prompt": "Lifespan of an adult mayfly",
        "emoji": "🦟",
        "answer": 1,
        "money": False,
        "unit": "day",
        "fact": "Many adult mayflies live only about 1 day — just long enough to lay eggs.",
        "category": "animals",
    },
    {
        "prompt": "Arms on a typical starfish",
        "emoji": "⭐",
        "answer": 5,
        "money": False,
        "unit": "arms",
        "fact": "A starfish usually has 5 arms and can regrow one if it loses it.",
        "category": "animals",
    },
    {
        "prompt": "Times its own weight an ant can lift",
        "emoji": "🐜",
        "answer": 50,
        "money": False,
        "unit": "times",
        "fact": "An ant can lift up to 50 times its own weight — like you hoisting a car.",
        "category": "animals",
    },

    # ---------------- fun ----------------
    {
        "prompt": "Colors in a rainbow",
        "emoji": "🌈",
        "answer": 7,
        "money": False,
        "unit": "colors",
        "fact": "A rainbow has 7 colors — remember ROY G BIV to name them in order.",
        "category": "fun",
    },
    {
        "prompt": "Days in a leap year",
        "emoji": "📆",
        "answer": 366,
        "money": False,
        "unit": "days",
        "fact": "A leap year has 366 days, adding February 29th every four years.",
        "category": "fun",
    },
    {
        "prompt": "Hours in a day",
        "emoji": "⏰",
        "answer": 24,
        "money": False,
        "unit": "hours",
        "fact": "A day has 24 hours — the time it takes Earth to spin around once.",
        "category": "fun",
    },
    {
        "prompt": "Days in a week",
        "emoji": "🗓️",
        "answer": 7,
        "money": False,
        "unit": "days",
        "fact": "A week is 7 days — a tradition thousands of years old.",
        "category": "fun",
    },
    {
        "prompt": "Dwarfs in the story of Snow White",
        "emoji": "⛏️",
        "answer": 7,
        "money": False,
        "unit": "dwarfs",
        "fact": "Snow White meets 7 dwarfs, from Doc to Sleepy to Grumpy.",
        "category": "fun",
    },
    {
        "prompt": "Books in the Harry Potter series",
        "emoji": "⚡",
        "answer": 7,
        "money": False,
        "unit": "books",
        "fact": "There are 7 Harry Potter books, one for each year at Hogwarts.",
        "category": "fun",
    },
    {
        "prompt": "Films in the Star Wars Skywalker saga",
        "emoji": "🌟",
        "answer": 9,
        "money": False,
        "unit": "films",
        "fact": "The main Skywalker saga is 9 films, released across more than 40 years.",
        "category": "fun",
    },
    {
        "prompt": "Spaces on a Monopoly board",
        "emoji": "🎩",
        "answer": 40,
        "money": False,
        "unit": "spaces",
        "fact": "A Monopoly board has 40 spaces — Boardwalk is the priciest of them all.",
        "category": "fun",
    },
    {
        "prompt": "Letter tiles in a Scrabble set",
        "emoji": "🔡",
        "answer": 100,
        "money": False,
        "unit": "tiles",
        "fact": "Scrabble comes with 100 tiles, including 2 blanks that can be any letter.",
        "category": "fun",
    },
    {
        "prompt": "Chess pieces on the board at the start",
        "emoji": "♟️",
        "answer": 32,
        "money": False,
        "unit": "pieces",
        "fact": "A chess game starts with 32 pieces — 16 for each player.",
        "category": "fun",
    },
    {
        "prompt": "Dominoes in a double-six set",
        "emoji": "🁫",
        "answer": 28,
        "money": False,
        "unit": "dominoes",
        "fact": "A double-six domino set has 28 tiles, one for every pair of numbers.",
        "category": "fun",
    },
    {
        "prompt": "Total gifts given in 'The 12 Days of Christmas'",
        "emoji": "🎁",
        "answer": 364,
        "money": False,
        "unit": "gifts",
        "fact": "Add up every day and the song gives 364 gifts — almost one for each day of the year!",
        "category": "fun",
    },
    {
        "prompt": "Squares in a standard Hershey's milk chocolate bar",
        "emoji": "🍫",
        "answer": 12,
        "money": False,
        "unit": "squares",
        "fact": "A classic Hershey's bar snaps into 12 little squares — easy to share.",
        "category": "fun",
    },
    {
        "prompt": "White keys on a piano",
        "emoji": "🎹",
        "answer": 52,
        "money": False,
        "unit": "keys",
        "fact": "A piano has 52 white keys and 36 black ones, 88 in total.",
        "category": "fun",
    },
    {
        "prompt": "Seconds in one hour",
        "emoji": "⏳",
        "answer": 3600,
        "money": False,
        "unit": "seconds",
        "fact": "There are 3,600 seconds in an hour — 60 minutes times 60 seconds.",
        "category": "fun",
    },
    {
        "prompt": "Squares on a Scrabble board",
        "emoji": "🎯",
        "answer": 225,
        "money": False,
        "unit": "squares",
        "fact": "A Scrabble board is a 15-by-15 grid, making 225 squares in all.",
        "category": "fun",
    },
]
