"""TRIVIA question bank — the content IS the game, curated by hand.

Every entry: {"cat": slug, "diff": 1|2|3, "q": text,
              "choices": [4 strings, correct FIRST], "a": 0}
The bank always stores the correct answer at index 0 ("a": 0); the game
shuffles choice order per match. Curation rules: timeless verifiable facts
only (nothing that rots, no "currently/most recent"), family-safe, no trick
wording, distractors plausible but clearly wrong.

diff 1 = the youngest player can get it, 2 = family standard, 3 = grown-up.
"""

import re
import unicodedata


def _q(cat, diff, text, correct, w1, w2, w3):
    return {"cat": cat, "diff": diff, "q": text,
            "choices": [correct, w1, w2, w3], "a": 0}


CATEGORIES = [
    ("general",   "General Knowledge", "🧠"),
    ("science",   "Science & Nature",  "🔬"),
    ("geography", "Geography",         "🌍"),
    ("movies",    "Movies & TV",       "🎬"),
    ("music",     "Music",             "🎵"),
    ("sports",    "Sports",            "🏅"),
    ("history",   "History",           "🏛️"),
    ("food",      "Food & Drink",      "🍕"),
    ("animals",   "Animals",           "🐾"),
    ("kids",      "Kids Zone",         "🧒"),
]

BANK = [
    # ================= GENERAL KNOWLEDGE =================
    _q("general", 1, "How many days are in a leap year?", "366", "365", "364", "367"),
    _q("general", 1, "How many sides does a triangle have?", "3", "4", "5", "6"),
    _q("general", 1, "What do bees make?", "Honey", "Milk", "Silk", "Butter"),
    _q("general", 1, "How many letters are in the English alphabet?", "26", "24", "25", "27"),
    _q("general", 1, "What color do you get by mixing blue and yellow paint?", "Green", "Purple", "Orange", "Brown"),
    _q("general", 1, "How many minutes are in one hour?", "60", "100", "30", "90"),
    _q("general", 1, "Which month has only 28 days in a normal year?", "February", "January", "April", "November"),
    _q("general", 1, "How many wheels does a tricycle have?", "3", "2", "4", "1"),
    _q("general", 1, "What is frozen water called?", "Ice", "Steam", "Fog", "Dew"),
    _q("general", 1, "How many days are in a week?", "7", "5", "6", "8"),
    _q("general", 1, "Which shape has four equal sides and four right angles?", "Square", "Triangle", "Circle", "Oval"),
    _q("general", 1, "What do you call a baby dog?", "Puppy", "Kitten", "Cub", "Foal"),
    _q("general", 1, "How many hours are in a day?", "24", "12", "20", "48"),
    _q("general", 1, "Which of these is a primary color of paint?", "Red", "Green", "Orange", "Purple"),
    _q("general", 1, "What instrument tells you the time?", "Clock", "Ruler", "Scale", "Thermometer"),
    _q("general", 1, "How many cents make a dollar?", "100", "50", "10", "1000"),
    _q("general", 1, "Which season comes after winter?", "Spring", "Summer", "Fall", "Autumn again"),
    _q("general", 1, "What do you use an umbrella for?", "Keeping dry in rain", "Digging holes", "Cooking food", "Cutting paper"),
    _q("general", 1, "Which direction does the sun rise from?", "East", "West", "North", "South"),
    _q("general", 1, "How many fingers and thumbs do most people have in total?", "10", "8", "12", "20"),
    _q("general", 2, "How many sides does a hexagon have?", "6", "5", "7", "8"),
    _q("general", 2, "What is H2O more commonly known as?", "Water", "Salt", "Hydrogen peroxide", "Oxygen"),
    _q("general", 2, "How many keys does a standard full-size piano have?", "88", "76", "100", "64"),
    _q("general", 2, "In Roman numerals, what number is X?", "10", "5", "50", "100"),
    _q("general", 2, "How many degrees are in a right angle?", "90", "45", "180", "60"),
    _q("general", 2, "What is the largest planet in our solar system?", "Jupiter", "Saturn", "Neptune", "Earth"),
    _q("general", 2, "How many strings does a standard guitar have?", "6", "4", "5", "8"),
    _q("general", 2, "Which language has the most native speakers in the world?", "Mandarin Chinese", "English", "Spanish", "Hindi"),
    _q("general", 2, "How many squares are on a chessboard (8 by 8)?", "64", "56", "72", "81"),
    _q("general", 2, "What does 'www' stand for in a website address?", "World Wide Web", "World Web Window", "Wide World Web", "Web World Wide"),
    _q("general", 2, "How many zeros are in one million?", "6", "5", "7", "9"),
    _q("general", 2, "Which planet is known as the Red Planet?", "Mars", "Venus", "Jupiter", "Mercury"),
    _q("general", 2, "What is a group of lions called?", "A pride", "A pack", "A herd", "A flock"),
    _q("general", 2, "How many pieces does each player start with in a game of chess?", "16", "12", "15", "18"),
    _q("general", 2, "What does a spider spin to catch insects?", "A web", "A nest", "A cocoon", "A hive"),
    _q("general", 2, "In the fairy tale, who left a glass slipper at the ball?", "Cinderella", "Snow White", "Rapunzel", "Sleeping Beauty"),
    _q("general", 2, "How many sides does an octagon have?", "8", "6", "7", "9"),
    _q("general", 2, "What does a thermometer measure?", "Temperature", "Wind speed", "Rainfall", "Air pressure"),
    _q("general", 2, "Which chess piece can only move diagonally?", "Bishop", "Rook", "Knight", "King"),
    _q("general", 2, "What is the name of the fairy in Peter Pan?", "Tinker Bell", "Wendy", "Aurora", "Ariel"),
    _q("general", 3, "How many dots are on a standard six-sided die in total?", "21", "18", "24", "20"),
    _q("general", 3, "In Roman numerals, what does C represent?", "100", "50", "500", "1000"),
    _q("general", 3, "What is the smallest prime number?", "2", "1", "3", "0"),
    _q("general", 3, "How many degrees do the angles of any triangle add up to?", "180", "90", "270", "360"),
    _q("general", 3, "Which metal is liquid at room temperature?", "Mercury", "Lead", "Tin", "Aluminum"),
    _q("general", 3, "What is the square root of 144?", "12", "14", "11", "16"),
    _q("general", 3, "How many faces does a cube have?", "6", "4", "8", "12"),
    _q("general", 3, "Which word describes a word that reads the same forwards and backwards?", "Palindrome", "Anagram", "Acronym", "Homonym"),
    _q("general", 3, "How many milliliters are in one liter?", "1000", "100", "10", "10000"),
    _q("general", 3, "What is the seventh planet from the sun?", "Uranus", "Neptune", "Saturn", "Jupiter"),
    _q("general", 3, "In a deck of standard playing cards, how many are face cards (J, Q, K)?", "12", "8", "16", "10"),
    _q("general", 3, "What does the 'SOS' distress signal consist of in Morse code?", "Three dots, three dashes, three dots", "Three dashes, three dots, three dashes", "Six dots", "Six dashes"),
    _q("general", 3, "How many years are in a millennium?", "1000", "100", "10000", "500"),
    _q("general", 3, "Which of these numbers is a prime number?", "17", "15", "21", "27"),
    _q("general", 3, "What is one dozen plus one score?", "32", "22", "30", "24"),
    _q("general", 3, "The Mona Lisa was painted by which artist?", "Leonardo da Vinci", "Michelangelo", "Raphael", "Vincent van Gogh"),
    _q("general", 3, "How many time zones does the world officially span (whole-hour standard)?", "24", "12", "36", "48"),
    _q("general", 3, "What is the collective noun for a group of crows?", "A murder", "A gaggle", "A parliament", "A swarm"),
    _q("general", 3, "Which two colors mixed together make purple?", "Red and blue", "Red and yellow", "Blue and yellow", "Red and green"),
    _q("general", 3, "How many sides does a dodecagon have?", "12", "10", "11", "20"),

    # ================= SCIENCE & NATURE =================
    _q("science", 1, "What planet do we live on?", "Earth", "Mars", "Venus", "Jupiter"),
    _q("science", 1, "What do plants need from the sun to grow?", "Light", "Sound", "Wind", "Snow"),
    _q("science", 1, "What gas do humans need to breathe to live?", "Oxygen", "Helium", "Carbon dioxide", "Hydrogen"),
    _q("science", 1, "What is the center of our solar system?", "The Sun", "The Moon", "Earth", "Mars"),
    _q("science", 1, "What falls from clouds when it rains?", "Water", "Sand", "Leaves", "Dust"),
    _q("science", 1, "How many legs does an insect have?", "6", "4", "8", "10"),
    _q("science", 1, "What part of your body pumps blood?", "Heart", "Brain", "Lungs", "Stomach"),
    _q("science", 1, "What do caterpillars turn into?", "Butterflies", "Bees", "Ladybugs", "Dragonflies"),
    _q("science", 1, "Which of these is NOT a state of matter?", "Wood", "Solid", "Liquid", "Gas"),
    _q("science", 1, "What do you call molten rock that erupts from a volcano?", "Lava", "Mud", "Steam", "Ash"),
    _q("science", 1, "Which body part do you use to smell?", "Nose", "Ears", "Eyes", "Hands"),
    _q("science", 1, "What natural satellite orbits the Earth?", "The Moon", "The Sun", "Mars", "A comet"),
    _q("science", 1, "What season do many trees lose their leaves?", "Fall", "Summer", "Spring", "Winter solstice only"),
    _q("science", 1, "What do you call a scientist who studies dinosaurs?", "Paleontologist", "Astronomer", "Chemist", "Geographer"),
    _q("science", 1, "Which of these animals is a mammal?", "Dolphin", "Shark", "Octopus", "Salmon"),
    _q("science", 2, "What is the chemical symbol for gold?", "Au", "Ag", "Go", "Gd"),
    _q("science", 2, "How many bones are in the adult human body?", "206", "106", "306", "250"),
    _q("science", 2, "What force pulls objects toward the Earth?", "Gravity", "Magnetism", "Friction", "Momentum"),
    _q("science", 2, "What is the hardest natural substance on Earth?", "Diamond", "Gold", "Iron", "Quartz"),
    _q("science", 2, "What gas do plants absorb from the air?", "Carbon dioxide", "Oxygen", "Nitrogen", "Helium"),
    _q("science", 2, "What is the boiling point of water at sea level in Celsius?", "100 degrees", "90 degrees", "110 degrees", "212 degrees"),
    _q("science", 2, "Which planet is closest to the sun?", "Mercury", "Venus", "Mars", "Earth"),
    _q("science", 2, "What are the three states of matter you see every day?", "Solid, liquid, gas", "Hot, cold, warm", "Rock, water, air", "Hard, soft, wet"),
    _q("science", 2, "What organ controls your whole body?", "Brain", "Heart", "Liver", "Spine"),
    _q("science", 2, "What is the largest organ of the human body?", "Skin", "Liver", "Brain", "Lungs"),
    _q("science", 2, "What type of energy comes from the sun?", "Solar energy", "Nuclear energy", "Wind energy", "Geothermal energy"),
    _q("science", 2, "How many planets are in our solar system?", "8", "9", "7", "10"),
    _q("science", 2, "What is the process by which plants make their food called?", "Photosynthesis", "Respiration", "Digestion", "Fermentation"),
    _q("science", 2, "What instrument is used to look at very small things?", "Microscope", "Telescope", "Periscope", "Stethoscope"),
    _q("science", 2, "Sound travels fastest through which of these?", "Steel", "Air", "Water", "A vacuum"),
    _q("science", 2, "What vitamin does your skin make when exposed to sunlight?", "Vitamin D", "Vitamin C", "Vitamin A", "Vitamin B12"),
    _q("science", 2, "What is the closest star to Earth?", "The Sun", "Polaris", "Alpha Centauri", "Sirius"),
    _q("science", 2, "Which blood cells help your body fight infection?", "White blood cells", "Red blood cells", "Platelets", "Plasma cells"),
    _q("science", 2, "What is water made of?", "Hydrogen and oxygen", "Oxygen and carbon", "Hydrogen and nitrogen", "Carbon and nitrogen"),
    _q("science", 2, "Which planet is famous for its large rings?", "Saturn", "Mars", "Venus", "Mercury"),
    _q("science", 2, "What do you call an animal that eats only plants?", "Herbivore", "Carnivore", "Omnivore", "Insectivore"),
    _q("science", 2, "What tiny unit are all living things made of?", "Cells", "Atoms of gold", "Grains", "Crystals"),
    _q("science", 2, "Which gas makes up most of the air we breathe?", "Nitrogen", "Oxygen", "Carbon dioxide", "Hydrogen"),
    _q("science", 2, "What natural event is measured by the Richter scale?", "Earthquakes", "Hurricanes", "Tornadoes", "Floods"),
    _q("science", 2, "How long does Earth take to orbit the sun once?", "About 365 days", "About 30 days", "About 24 hours", "About 100 days"),
    _q("science", 3, "What is the chemical symbol for iron?", "Fe", "Ir", "In", "Fr"),
    _q("science", 3, "What part of the cell contains its genetic material?", "Nucleus", "Cell wall", "Cytoplasm", "Membrane"),
    _q("science", 3, "Approximately how fast does light travel in a vacuum?", "300,000 km per second", "300,000 km per hour", "3,000 km per second", "30,000 km per second"),
    _q("science", 3, "What is the most abundant element in the universe?", "Hydrogen", "Oxygen", "Helium", "Carbon"),
    _q("science", 3, "What kind of animal is a Komodo dragon?", "Lizard", "Snake", "Crocodile", "Dinosaur"),
    _q("science", 3, "At what temperature are Celsius and Fahrenheit equal?", "-40 degrees", "0 degrees", "-32 degrees", "100 degrees"),
    _q("science", 3, "What is the study of weather called?", "Meteorology", "Geology", "Astronomy", "Ecology"),
    _q("science", 3, "Which particle in an atom has a negative charge?", "Electron", "Proton", "Neutron", "Photon"),
    _q("science", 3, "DNA stands for deoxyribonucleic what?", "Acid", "Atom", "Agent", "Antibody"),
    _q("science", 3, "What is the chemical formula for table salt?", "NaCl", "KCl", "CaCl2", "NaOH"),
    _q("science", 3, "Which layer of Earth lies at its very center?", "Inner core", "Crust", "Mantle", "Outer core"),
    _q("science", 3, "What unit measures electrical resistance?", "Ohm", "Volt", "Ampere", "Watt"),
    _q("science", 3, "Which scientist proposed the three laws of motion?", "Isaac Newton", "Albert Einstein", "Galileo Galilei", "Charles Darwin"),
    _q("science", 3, "What is the largest type of star explosion called?", "Supernova", "Solar flare", "Meteor shower", "Aurora"),
    _q("science", 3, "What pigment makes plant leaves green?", "Chlorophyll", "Melanin", "Carotene", "Keratin"),
    _q("science", 3, "Which planet spins on its side compared to the others?", "Uranus", "Neptune", "Mercury", "Mars"),
    _q("science", 3, "What is the smallest bone in the human body, found in the ear?", "Stapes", "Femur", "Radius", "Patella"),
    _q("science", 3, "Which element has the atomic number 1?", "Hydrogen", "Helium", "Oxygen", "Carbon"),
    _q("science", 3, "What do you call the change of a liquid into a gas?", "Evaporation", "Condensation", "Freezing", "Sublimation"),
    _q("science", 3, "Which blood type is known as the universal donor?", "O negative", "AB positive", "A positive", "B negative"),

    # ================= GEOGRAPHY =================
    _q("geography", 1, "Which is the largest ocean on Earth?", "Pacific", "Atlantic", "Indian", "Arctic"),
    _q("geography", 1, "What is the frozen continent at the bottom of the world called?", "Antarctica", "Australia", "Africa", "Greenland"),
    _q("geography", 1, "Which country is shaped like a boot?", "Italy", "France", "Spain", "Portugal"),
    _q("geography", 1, "What do you call a piece of land completely surrounded by water?", "An island", "A peninsula", "A valley", "A plateau"),
    _q("geography", 1, "Which of these is a desert?", "The Sahara", "The Amazon", "The Alps", "The Nile"),
    _q("geography", 1, "In which country would you find kangaroos in the wild?", "Australia", "Brazil", "India", "Kenya"),
    _q("geography", 1, "What is the capital of the United States?", "Washington, D.C.", "New York City", "Los Angeles", "Chicago"),
    _q("geography", 1, "Which country is famous for the Eiffel Tower?", "France", "Italy", "Germany", "Spain"),
    _q("geography", 1, "How many continents are there?", "7", "5", "6", "8"),
    _q("geography", 1, "Which U.S. state is famous for Hollywood?", "California", "Florida", "Texas", "Nevada"),
    _q("geography", 1, "What is a mountain that can erupt called?", "A volcano", "A glacier", "A canyon", "A geyser"),
    _q("geography", 1, "Which country is home to the Great Wall?", "China", "Japan", "India", "Egypt"),
    _q("geography", 1, "The North Pole is covered mostly by what?", "Ice", "Sand", "Grass", "Forest"),
    _q("geography", 1, "Which of these is one of the Great Lakes?", "Lake Michigan", "Lake Tahoe", "Great Salt Lake", "Lake Placid"),
    _q("geography", 1, "Mount Everest is the world's tallest what?", "Mountain", "Volcano", "Waterfall", "Glacier"),
    _q("geography", 2, "What is the capital of France?", "Paris", "Lyon", "Marseille", "Nice"),
    _q("geography", 2, "What is the longest river in South America?", "The Amazon", "The Mississippi", "The Nile", "The Danube"),
    _q("geography", 2, "Which country has the largest population in Africa?", "Nigeria", "Egypt", "South Africa", "Kenya"),
    _q("geography", 2, "What is the capital of Japan?", "Tokyo", "Kyoto", "Osaka", "Seoul"),
    _q("geography", 2, "The Statue of Liberty was a gift to the USA from which country?", "France", "England", "Italy", "Spain"),
    _q("geography", 2, "Which U.S. state is the largest by area?", "Alaska", "Texas", "California", "Montana"),
    _q("geography", 2, "What is the capital of Italy?", "Rome", "Milan", "Venice", "Florence"),
    _q("geography", 2, "Which two countries share the longest international border?", "USA and Canada", "USA and Mexico", "Russia and China", "Brazil and Argentina"),
    _q("geography", 2, "The Great Barrier Reef is off the coast of which country?", "Australia", "Brazil", "Mexico", "Indonesia"),
    _q("geography", 2, "Which continent is the Sahara Desert in?", "Africa", "Asia", "Australia", "South America"),
    _q("geography", 2, "What is the capital of Canada?", "Ottawa", "Toronto", "Vancouver", "Montreal"),
    _q("geography", 2, "Which ocean is between Europe and North America?", "Atlantic", "Pacific", "Indian", "Arctic"),
    _q("geography", 2, "Which country do the Pyramids of Giza stand in?", "Egypt", "Mexico", "Greece", "Morocco"),
    _q("geography", 2, "What is the capital of Spain?", "Madrid", "Barcelona", "Seville", "Lisbon"),
    _q("geography", 2, "Which mountain range separates Europe from Asia?", "The Urals", "The Alps", "The Andes", "The Rockies"),
    _q("geography", 2, "The city of Venice in Italy is famous for its what?", "Canals", "Skyscrapers", "Deserts", "Volcanoes"),
    _q("geography", 2, "Which U.S. state is nicknamed the Sunshine State?", "Florida", "California", "Arizona", "Hawaii"),
    _q("geography", 2, "What is the largest country in the world by area?", "Russia", "Canada", "China", "USA"),
    _q("geography", 2, "Which country is home to the city of Rio de Janeiro?", "Brazil", "Argentina", "Portugal", "Mexico"),
    _q("geography", 2, "The Grand Canyon is located in which U.S. state?", "Arizona", "Colorado", "Utah", "Nevada"),
    _q("geography", 2, "What is the capital of the United Kingdom?", "London", "Manchester", "Edinburgh", "Dublin"),
    _q("geography", 2, "Which continent has the most countries?", "Africa", "Europe", "Asia", "South America"),
    _q("geography", 2, "Which sea is so salty that people float easily in it?", "The Dead Sea", "The Red Sea", "The Black Sea", "The Baltic Sea"),
    _q("geography", 2, "What imaginary line divides the Earth into Northern and Southern halves?", "The Equator", "The Prime Meridian", "The Tropic of Cancer", "The Date Line"),
    _q("geography", 2, "Which country's flag is a red circle on a white background?", "Japan", "China", "South Korea", "Vietnam"),
    _q("geography", 3, "What is the capital of Australia?", "Canberra", "Sydney", "Melbourne", "Perth"),
    _q("geography", 3, "Which African river flows north into the Mediterranean?", "The Nile", "The Congo", "The Zambezi", "The Niger"),
    _q("geography", 3, "Which country has both Rome and Vatican City inside its borders?", "Italy", "Greece", "Spain", "France"),
    _q("geography", 3, "What is the smallest country in the world?", "Vatican City", "Monaco", "Malta", "Liechtenstein"),
    _q("geography", 3, "Which strait separates Europe from Africa at Spain and Morocco?", "Strait of Gibraltar", "Bosphorus Strait", "Bering Strait", "Strait of Hormuz"),
    _q("geography", 3, "What is the capital of Brazil?", "Brasília", "Rio de Janeiro", "São Paulo", "Buenos Aires"),
    _q("geography", 3, "Which mountain range contains Mount Everest?", "The Himalayas", "The Andes", "The Alps", "The Rockies"),
    _q("geography", 3, "Which U.S. river flows past New Orleans into the Gulf of Mexico?", "The Mississippi", "The Colorado", "The Ohio", "The Hudson"),
    _q("geography", 3, "What is the capital of Egypt?", "Cairo", "Alexandria", "Giza", "Casablanca"),
    _q("geography", 3, "Which country is called the Land of the Rising Sun?", "Japan", "China", "Thailand", "South Korea"),
    _q("geography", 3, "Lake Baikal, the world's deepest lake, is in which country?", "Russia", "Canada", "China", "Finland"),
    _q("geography", 3, "Which desert covers much of Mongolia and northern China?", "The Gobi", "The Sahara", "The Kalahari", "The Mojave"),
    _q("geography", 3, "What is the capital of Greece?", "Athens", "Sparta", "Thessaloniki", "Crete"),
    _q("geography", 3, "Which canal connects the Atlantic and Pacific Oceans?", "The Panama Canal", "The Suez Canal", "The Erie Canal", "The Kiel Canal"),
    _q("geography", 3, "Which country has the most natural lakes?", "Canada", "USA", "Russia", "Brazil"),
    _q("geography", 3, "What is the capital of Germany?", "Berlin", "Munich", "Frankfurt", "Hamburg"),
    _q("geography", 3, "Angel Falls, the world's tallest waterfall, is in which country?", "Venezuela", "Brazil", "Peru", "Colombia"),
    _q("geography", 3, "Which two continents does Turkey span?", "Europe and Asia", "Asia and Africa", "Europe and Africa", "Asia and Oceania"),
    _q("geography", 3, "What is the capital of Russia?", "Moscow", "St. Petersburg", "Kiev", "Minsk"),
    _q("geography", 3, "Which island nation lies directly south of Florida?", "Cuba", "Jamaica", "Puerto Rico", "Haiti"),

    # ================= MOVIES & TV =================
    _q("movies", 1, "In 'Frozen', what is the name of Elsa's sister?", "Anna", "Belle", "Moana", "Rapunzel"),
    _q("movies", 1, "What kind of animal is Nemo in 'Finding Nemo'?", "Clownfish", "Shark", "Turtle", "Seahorse"),
    _q("movies", 1, "Who is the cowboy doll in 'Toy Story'?", "Woody", "Buzz", "Rex", "Slinky"),
    _q("movies", 1, "In 'The Lion King', what kind of animal is Simba?", "Lion", "Tiger", "Cheetah", "Leopard"),
    _q("movies", 1, "What color is the ogre Shrek?", "Green", "Blue", "Purple", "Orange"),
    _q("movies", 1, "In 'Moana', what kind of place does Moana live?", "An island", "A castle", "A city", "A forest"),
    _q("movies", 1, "Which movie features a talking snowman named Olaf?", "Frozen", "Moana", "Tangled", "Brave"),
    _q("movies", 1, "What is the name of Mickey Mouse's dog?", "Pluto", "Goofy", "Max", "Rex"),
    _q("movies", 1, "In 'Aladdin', what grants three wishes?", "The Genie", "The Carpet", "The Sultan", "The Lamp Merchant"),
    _q("movies", 1, "What kind of creature is Dory in 'Finding Nemo'?", "A fish", "A whale", "An octopus", "A dolphin"),
    _q("movies", 1, "In 'Beauty and the Beast', what does Belle love to do?", "Read books", "Bake bread", "Sing opera", "Paint pictures"),
    _q("movies", 1, "Which superhero carries a round shield with a star on it?", "Captain America", "Iron Man", "Thor", "Hulk"),
    _q("movies", 1, "What is the name of the family in 'The Incredibles'?", "The Parrs", "The Smiths", "The Waynes", "The Kents"),
    _q("movies", 1, "In 'Cars', what kind of vehicle is Lightning McQueen?", "A race car", "A truck", "A tractor", "A school bus"),
    _q("movies", 1, "SpongeBob SquarePants lives in a house shaped like what?", "A pineapple", "A shell", "A rock", "A boat"),
    _q("movies", 2, "In 'Star Wars', who is Luke Skywalker's father?", "Darth Vader", "Obi-Wan Kenobi", "Yoda", "Han Solo"),
    _q("movies", 2, "What school does Harry Potter attend?", "Hogwarts", "Oxford", "Narnia Academy", "Rivendell School"),
    _q("movies", 2, "Which superhero is known as the Man of Steel?", "Superman", "Batman", "Spider-Man", "Iron Man"),
    _q("movies", 2, "In 'The Wizard of Oz', what does Dorothy click together to go home?", "Her ruby slippers", "Her gloves", "Her earrings", "Her braids"),
    _q("movies", 2, "What is the name of the wizard in 'The Lord of the Rings'?", "Gandalf", "Dumbledore", "Merlin", "Radagast"),
    _q("movies", 2, "Which movie features a great white shark terrorizing a beach town?", "Jaws", "The Meg", "Sharknado", "Moby Dick"),
    _q("movies", 2, "In 'E.T.', what does E.T. want to do?", "Phone home", "Rule Earth", "Find gold", "Learn to fly a plane"),
    _q("movies", 2, "What is Batman's real identity?", "Bruce Wayne", "Clark Kent", "Peter Parker", "Tony Stark"),
    _q("movies", 2, "Which movie has the line 'May the Force be with you'?", "Star Wars", "Star Trek", "Avatar", "Guardians of the Galaxy"),
    _q("movies", 2, "In 'Jurassic Park', what are brought back to life?", "Dinosaurs", "Mammoths", "Dragons", "Aliens"),
    _q("movies", 2, "What is the name of the boy raised by wolves in 'The Jungle Book'?", "Mowgli", "Tarzan", "Bagheera", "Kaa"),
    _q("movies", 2, "Spider-Man got his powers from what?", "A spider bite", "A lab potion", "A magic ring", "Being born on another planet"),
    _q("movies", 2, "In 'Willy Wonka', what kind of factory does Wonka run?", "A chocolate factory", "A toy factory", "A bubble gum factory only", "A cookie factory"),
    _q("movies", 2, "Which movie features the song 'Hakuna Matata'?", "The Lion King", "The Jungle Book", "Madagascar", "Tarzan"),
    _q("movies", 2, "What is the name of Han Solo's ship in Star Wars?", "The Millennium Falcon", "The Enterprise", "The Serenity", "The X-Wing"),
    _q("movies", 2, "In 'Home Alone', what is the boy's name?", "Kevin", "Michael", "Tommy", "Buzz"),
    _q("movies", 2, "Which green Jedi Master trains Luke Skywalker?", "Yoda", "Obi-Wan", "Mace Windu", "Qui-Gon Jinn"),
    _q("movies", 2, "In 'Ratatouille', what does Remy the rat love to do?", "Cook", "Paint", "Sing", "Dance"),
    _q("movies", 2, "Which movie features a DeLorean time machine?", "Back to the Future", "The Terminator", "Men in Black", "Bill and Ted"),
    _q("movies", 2, "What are the small yellow creatures in 'Despicable Me' called?", "Minions", "Gnomes", "Smurfs", "Ewoks"),
    _q("movies", 2, "In 'Up', how does the house fly?", "Balloons", "Rockets", "Wings", "A tornado"),
    _q("movies", 2, "Which TV family lives in Springfield and has a dad named Homer?", "The Simpsons", "The Flintstones", "The Griffins", "The Jetsons"),
    _q("movies", 2, "In 'Harry Potter', what sport is played on broomsticks?", "Quidditch", "Wizard polo", "Broomball", "Skyball"),
    _q("movies", 2, "What is the name of the lion in 'The Chronicles of Narnia'?", "Aslan", "Mufasa", "Leo", "Simba"),
    _q("movies", 2, "In 'Monsters, Inc.', what do the monsters collect from children?", "Screams", "Dreams", "Toys", "Teeth"),
    _q("movies", 3, "Who directed 'Jaws', 'E.T.', and 'Jurassic Park'?", "Steven Spielberg", "George Lucas", "James Cameron", "Ridley Scott"),
    _q("movies", 3, "In 'The Matrix', what color pill does Neo take?", "Red", "Blue", "Green", "White"),
    _q("movies", 3, "Which movie won the first Academy Award for Best Animated Feature?", "Shrek", "Toy Story", "Monsters, Inc.", "Finding Nemo"),
    _q("movies", 3, "What is Indiana Jones afraid of?", "Snakes", "Spiders", "Heights", "Rats"),
    _q("movies", 3, "In 'Rocky', what is Rocky Balboa's sport?", "Boxing", "Wrestling", "Karate", "Football"),
    _q("movies", 3, "Which actor played Jack in 'Titanic'?", "Leonardo DiCaprio", "Brad Pitt", "Tom Cruise", "Matt Damon"),
    _q("movies", 3, "In 'The Terminator', what famous line does the Terminator say?", "I'll be back", "Here's Johnny", "You talking to me", "Make my day"),
    _q("movies", 3, "What is the name of the hobbit played by Elijah Wood in 'The Lord of the Rings'?", "Frodo Baggins", "Bilbo Baggins", "Samwise Gamgee", "Peregrin Took"),
    _q("movies", 3, "In 'Ghostbusters', what giant creature stomps through New York?", "The Stay Puft Marshmallow Man", "King Kong", "Godzilla", "A giant slime blob"),
    _q("movies", 3, "Which movie features the line 'Life is like a box of chocolates'?", "Forrest Gump", "The Notebook", "Big", "Rain Man"),
    _q("movies", 3, "Who plays Iron Man in the Marvel movies?", "Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Mark Ruffalo"),
    _q("movies", 3, "In 'The Karate Kid', what chore teaches Daniel karate moves?", "Wax on, wax off", "Mow the lawn", "Wash the windows only", "Rake the leaves"),
    _q("movies", 3, "What is the fictional African nation in 'Black Panther'?", "Wakanda", "Zamunda", "Genovia", "Latveria"),
    _q("movies", 3, "Which 1993 movie stars Robin Williams as a nanny in disguise?", "Mrs. Doubtfire", "Jumanji", "Hook", "Patch Adams"),
    _q("movies", 3, "In 'Pirates of the Caribbean', who captains the Black Pearl?", "Jack Sparrow", "Hector Barbossa", "Will Turner", "Davy Jones"),
    _q("movies", 3, "What board game comes to life in the 1995 film 'Jumanji'?", "Jumanji", "Monopoly", "Zathura", "Clue"),
    _q("movies", 3, "In 'The Truman Show', what is Truman's life actually?", "A TV show", "A dream", "A video game", "A book"),
    _q("movies", 3, "Which composer wrote the scores for Star Wars, Jaws, and Harry Potter?", "John Williams", "Hans Zimmer", "Danny Elfman", "James Horner"),
    _q("movies", 3, "In 'King Kong', what building does Kong climb?", "The Empire State Building", "The Chrysler Building", "The Eiffel Tower", "Big Ben"),
    _q("movies", 3, "What is the name of Sherlock Holmes' loyal friend?", "Dr. Watson", "Inspector Lestrade", "Mycroft", "Moriarty"),

    # ================= MUSIC =================
    _q("music", 1, "Which instrument has black and white keys?", "Piano", "Guitar", "Drums", "Trumpet"),
    _q("music", 1, "What do you call a group of people singing together?", "A choir", "An orchestra", "A band of drummers", "A quartet of dancers"),
    _q("music", 1, "Which instrument do you hit with sticks?", "Drums", "Flute", "Violin", "Harp"),
    _q("music", 1, "In 'Old MacDonald Had a Farm', what does he have?", "A farm", "A zoo", "A boat", "A store"),
    _q("music", 1, "Which instrument has six strings and is played by strumming?", "Guitar", "Piano", "Trumpet", "Xylophone"),
    _q("music", 1, "What song do you sing on someone's birthday?", "Happy Birthday to You", "Jingle Bells", "Twinkle Twinkle", "The ABC Song"),
    _q("music", 1, "Which of these is a brass instrument?", "Trumpet", "Violin", "Piano", "Maracas"),
    _q("music", 1, "'Twinkle, Twinkle, Little...' what?", "Star", "Moon", "Sun", "Light"),
    _q("music", 1, "What instrument does a drummer play?", "Drums", "Keyboard", "Saxophone", "Cello"),
    _q("music", 1, "Which instrument do you blow into and slide to change notes?", "Trombone", "Violin", "Banjo", "Piano"),
    _q("music", 1, "In the song, what animal did Mary have that followed her to school?", "A little lamb", "A puppy", "A kitten", "A pony"),
    _q("music", 1, "Maracas make music when you do what with them?", "Shake them", "Blow into them", "Pluck them", "Bow them"),
    _q("music", 2, "Which band recorded 'Hey Jude' and 'Let It Be'?", "The Beatles", "The Rolling Stones", "The Beach Boys", "Queen"),
    _q("music", 2, "Who is known as the King of Rock and Roll?", "Elvis Presley", "Chuck Berry", "Johnny Cash", "Buddy Holly"),
    _q("music", 2, "Which singer is known as the King of Pop?", "Michael Jackson", "Prince", "Elton John", "Stevie Wonder"),
    _q("music", 2, "How many strings does a violin have?", "4", "6", "5", "8"),
    _q("music", 2, "Which band sang 'Bohemian Rhapsody'?", "Queen", "The Beatles", "Led Zeppelin", "Pink Floyd"),
    _q("music", 2, "What are the five lines that music notes are written on called?", "A staff", "A ladder", "A scale", "A bar chart"),
    _q("music", 2, "Which country did The Beatles come from?", "England", "USA", "Australia", "Ireland"),
    _q("music", 2, "Which large string instrument sits on the floor and is played sitting down?", "Cello", "Violin", "Viola", "Ukulele"),
    _q("music", 2, "Beethoven and Mozart were famous what?", "Composers", "Painters", "Dancers", "Poets"),
    _q("music", 2, "Which small four-stringed instrument is linked with Hawaii?", "Ukulele", "Banjo", "Mandolin", "Fiddle"),
    _q("music", 2, "Who sang 'I Will Always Love You' in 'The Bodyguard'?", "Whitney Houston", "Mariah Carey", "Celine Dion", "Diana Ross"),
    _q("music", 2, "What does a conductor use to lead an orchestra?", "A baton", "A whistle", "A drumstick", "A flag"),
    _q("music", 2, "Which of these is a woodwind instrument?", "Clarinet", "Trumpet", "Cello", "Timpani"),
    _q("music", 2, "Elton John sang about what kind of 'Road'?", "Goodbye Yellow Brick Road", "Abbey Road", "Country Road", "Thunder Road"),
    _q("music", 2, "Who sang 'Purple Rain'?", "Prince", "Michael Jackson", "David Bowie", "Lenny Kravitz"),
    _q("music", 2, "How many musicians are in a quartet?", "4", "3", "5", "2"),
    _q("music", 2, "Which holiday song mentions a one-horse open sleigh?", "Jingle Bells", "Silent Night", "Deck the Halls", "Frosty the Snowman"),
    _q("music", 2, "Bob Marley made which style of music famous worldwide?", "Reggae", "Jazz", "Country", "Opera"),
    _q("music", 2, "Which instrument is Louis Armstrong famous for playing?", "Trumpet", "Saxophone", "Piano", "Clarinet"),
    _q("music", 2, "Taylor Swift started her career in which music genre?", "Country", "Hip hop", "Opera", "Punk rock"),
    _q("music", 2, "What is the highest female singing voice called?", "Soprano", "Alto", "Tenor", "Bass"),
    _q("music", 2, "Which band sang 'Yellow Submarine'?", "The Beatles", "The Monkees", "The Who", "The Kinks"),
    _q("music", 2, "The song 'Let It Go' comes from which movie?", "Frozen", "Moana", "Encanto", "Tangled"),
    _q("music", 2, "Which instrument has pedals, strings, and is often played at weddings and in orchestras — you pluck it upright?", "Harp", "Organ", "Accordion", "Cello"),
    _q("music", 3, "Which composer wrote the 'Fifth Symphony' that starts da-da-da-DUM?", "Beethoven", "Mozart", "Bach", "Brahms"),
    _q("music", 3, "Freddie Mercury was the lead singer of which band?", "Queen", "The Who", "AC/DC", "Aerosmith"),
    _q("music", 3, "Which city is considered the birthplace of jazz?", "New Orleans", "New York", "Chicago", "Memphis"),
    _q("music", 3, "How many notes are in a musical octave, from do to the next do?", "8", "7", "10", "12"),
    _q("music", 3, "Which band released the album 'The Dark Side of the Moon'?", "Pink Floyd", "Led Zeppelin", "The Rolling Stones", "The Doors"),
    _q("music", 3, "Johnny Cash famously sang about walking what?", "The Line", "The Dog", "The Plank", "The Mile"),
    _q("music", 3, "Which Beatles member wrote and sang 'Imagine' after the band split?", "John Lennon", "Paul McCartney", "George Harrison", "Ringo Starr"),
    _q("music", 3, "What Italian word in music means 'to play quietly'?", "Piano", "Forte", "Allegro", "Presto"),
    _q("music", 3, "Aretha Franklin was known as the Queen of what?", "Soul", "Pop", "Country", "Disco"),
    _q("music", 3, "Which rock band's members painted their faces and included Gene Simmons?", "KISS", "Metallica", "Guns N' Roses", "Motley Crue"),
    _q("music", 3, "The 'Four Seasons' violin concertos were composed by whom?", "Vivaldi", "Beethoven", "Chopin", "Handel"),
    _q("music", 3, "Which singer's fans are famously called 'Swifties'?", "Taylor Swift", "Ariana Grande", "Billie Eilish", "Adele"),
    _q("music", 3, "Which instrument did jazz legend Miles Davis play?", "Trumpet", "Saxophone", "Piano", "Double bass"),
    _q("music", 3, "'The Star-Spangled Banner' is the national anthem of which country?", "USA", "UK", "Canada", "Australia"),
    _q("music", 3, "Which band sang 'Stairway to Heaven'?", "Led Zeppelin", "Pink Floyd", "Deep Purple", "Black Sabbath"),
    _q("music", 3, "Dolly Parton is a legend of which music genre?", "Country", "Jazz", "Blues", "Gospel"),
    _q("music", 3, "What does 'a cappella' mean?", "Singing without instruments", "Singing very loudly", "Singing in Italian", "Singing in a church only"),
    _q("music", 3, "Which Beach Boys song title is also a positive feeling you pick up?", "Good Vibrations", "Sweet Emotions", "Happy Together", "Feeling Groovy"),
    _q("music", 3, "Which instrument family does the tuba belong to?", "Brass", "Woodwind", "Strings", "Percussion"),
    _q("music", 3, "Ludwig van Beethoven famously kept composing after losing his what?", "Hearing", "Sight", "Voice", "Left hand"),
    _q("music", 1, "Which part of your body do you use to hear music?", "Ears", "Eyes", "Nose", "Hands"),
    _q("music", 1, "In 'The Wheels on the Bus', what do the wheels do?", "Go round and round", "Beep beep beep", "Swish swish swish", "Open and shut"),
    _q("music", 2, "What are the words of a song called?", "Lyrics", "Notes", "Chords", "Verses only"),
    _q("music", 2, "Which keyboard instrument found in churches plays through big pipes?", "Organ", "Piano", "Harpsichord", "Accordion"),
    _q("music", 3, "Which famous tenor trio member sang 'Nessun Dorma' at the 1990 World Cup?", "Luciano Pavarotti", "Andrea Bocelli", "Enrico Caruso", "Josh Groban"),
    _q("music", 3, "Which U.S. city is home to country music's Grand Ole Opry?", "Nashville", "Memphis", "Austin", "Atlanta"),

    # ================= SPORTS =================
    _q("sports", 1, "In basketball, what do you throw the ball through to score?", "A hoop", "A goal net on the ground", "A hole", "A window"),
    _q("sports", 1, "Which sport uses a bat and a ball, with bases you run around?", "Baseball", "Soccer", "Hockey", "Tennis"),
    _q("sports", 1, "In soccer, which player is allowed to use their hands?", "The goalkeeper", "The striker", "The captain", "The referee's helper"),
    _q("sports", 1, "What color are tennis balls usually?", "Yellow-green", "Red", "Blue", "White"),
    _q("sports", 1, "Which sport do you do in a swimming pool?", "Swimming", "Skiing", "Cycling", "Climbing"),
    _q("sports", 1, "In bowling, how many pins do you try to knock down?", "10", "8", "12", "6"),
    _q("sports", 1, "Which sport is played on ice with skates and a puck?", "Ice hockey", "Basketball", "Volleyball", "Rugby"),
    _q("sports", 1, "What do you ride in the sport of BMX?", "A bicycle", "A horse", "A skateboard", "A boat"),
    _q("sports", 1, "In golf, what do you hit the ball into?", "A hole", "A net", "A basket", "A wall"),
    _q("sports", 1, "Which sport uses a shuttlecock (birdie)?", "Badminton", "Tennis", "Squash", "Ping pong"),
    _q("sports", 1, "How many players from one team are on a soccer field at once?", "11", "9", "10", "12"),
    _q("sports", 1, "What do karate students earn as they improve?", "Colored belts", "Medals every class", "Trophies every class", "Stars on their uniform"),
    _q("sports", 2, "How many points is a touchdown worth in American football (before the extra point)?", "6", "7", "3", "5"),
    _q("sports", 2, "How often are the Summer Olympic Games held?", "Every 4 years", "Every 2 years", "Every year", "Every 5 years"),
    _q("sports", 2, "In basketball, how many points is a shot from beyond the arc worth?", "3", "2", "4", "1"),
    _q("sports", 2, "In which country was the NBA founded?", "USA", "Canada", "Spain", "England"),
    _q("sports", 2, "What is a score of zero called in tennis?", "Love", "Nil", "Duck", "Blank"),
    _q("sports", 2, "Which sport is known as 'the beautiful game'?", "Soccer", "Basketball", "Cricket", "Baseball"),
    _q("sports", 2, "How many strikes make a strikeout in baseball?", "3", "4", "2", "5"),
    _q("sports", 2, "What is the name of the championship game of the NFL season?", "The Super Bowl", "The World Series", "The Grand Final", "The Rose Bowl"),
    _q("sports", 2, "In which sport would you perform a slam dunk?", "Basketball", "Volleyball", "Tennis", "Handball"),
    _q("sports", 2, "How many rings are on the Olympic flag?", "5", "4", "6", "7"),
    _q("sports", 2, "Which sport takes place at Wimbledon?", "Tennis", "Golf", "Cricket", "Rowing"),
    _q("sports", 2, "In baseball, how many outs end a team's half of the inning?", "3", "2", "4", "6"),
    _q("sports", 2, "What piece of equipment protects a hockey goalie's face?", "A mask", "A visor cap", "Sunglasses", "A scarf"),
    _q("sports", 2, "Which race covers 26.2 miles?", "A marathon", "A sprint", "A triathlon", "A relay"),
    _q("sports", 2, "In volleyball, how many times may one team touch the ball before it must cross the net?", "3", "2", "4", "5"),
    _q("sports", 2, "Which sport uses the terms 'strike', 'spare', and 'gutter'?", "Bowling", "Baseball", "Darts", "Cricket"),
    _q("sports", 2, "What trophy is awarded to the NHL champion?", "The Stanley Cup", "The World Cup", "The Ryder Cup", "The Grey Cup"),
    _q("sports", 2, "In which sport do competitors ride waves on a board?", "Surfing", "Rowing", "Sailing", "Diving"),
    _q("sports", 2, "How many holes are on a standard full golf course?", "18", "9", "20", "12"),
    _q("sports", 2, "Which sport features a pommel horse and uneven bars?", "Gymnastics", "Equestrian", "Wrestling", "Fencing"),
    _q("sports", 2, "The World Series is the championship of which sport?", "Baseball", "American football", "Basketball", "Soccer"),
    _q("sports", 2, "Which sport did Muhammad Ali dominate?", "Boxing", "Wrestling", "Karate", "Weightlifting"),
    _q("sports", 2, "In soccer, what card sends a player off the field?", "Red", "Yellow", "Blue", "Black"),
    _q("sports", 2, "Which of these is a swimming stroke?", "Butterfly", "Grasshopper", "Dragonfly", "Firefly"),
    _q("sports", 2, "How many bases must a batter touch to score a home run (including home)?", "4", "3", "5", "2"),
    _q("sports", 2, "Which winter sport uses a stone and brooms on ice?", "Curling", "Bobsled", "Luge", "Biathlon"),
    _q("sports", 3, "Which basketball legend wore number 23 for the Chicago Bulls?", "Michael Jordan", "LeBron James", "Kobe Bryant", "Magic Johnson"),
    _q("sports", 3, "In which country were the ancient Olympic Games held?", "Greece", "Italy", "Egypt", "Turkey"),
    _q("sports", 3, "How many players from one team are on a basketball court at once?", "5", "6", "7", "4"),
    _q("sports", 3, "Which country has won the most FIFA World Cups in men's soccer?", "Brazil", "Germany", "Argentina", "Italy"),
    _q("sports", 3, "What is a perfect game score in ten-pin bowling?", "300", "200", "250", "500"),
    _q("sports", 3, "Babe Ruth is a legend of which sport?", "Baseball", "Boxing", "Golf", "American football"),
    _q("sports", 3, "The Tour de France is a famous race in which sport?", "Cycling", "Running", "Sailing", "Motor racing"),
    _q("sports", 3, "Which sport features the events foil, epee, and saber?", "Fencing", "Archery", "Rowing", "Shooting"),
    _q("sports", 3, "Which golfer is nicknamed 'Tiger'?", "Eldrick Woods", "Jack Nicklaus", "Arnold Palmer", "Phil Mickelson"),
    _q("sports", 3, "How long is an Olympic swimming pool?", "50 meters", "25 meters", "100 meters", "75 meters"),
    _q("sports", 3, "Serena Williams is famous in which sport?", "Tennis", "Golf", "Track and field", "Gymnastics"),
    _q("sports", 3, "Which sport awards the green jacket at the Masters?", "Golf", "Tennis", "Horse racing", "Snooker"),
    _q("sports", 3, "In American football, how many points is a field goal worth?", "3", "2", "6", "1"),
    _q("sports", 3, "Pele was a legendary player from which country?", "Brazil", "Argentina", "Portugal", "Spain"),
    _q("sports", 3, "In tennis, what is it called when a game is tied at 40-40?", "Deuce", "Advantage", "Match point", "Let"),
    _q("sports", 3, "Which event combines swimming, cycling, and running?", "Triathlon", "Decathlon", "Pentathlon", "Biathlon"),
    _q("sports", 3, "In darts, what is the highest score from a single dart?", "60 (triple 20)", "50 (bullseye)", "20", "100"),
    _q("sports", 3, "Which country invented judo?", "Japan", "China", "Korea", "Thailand"),
    _q("sports", 3, "A hat-trick in soccer means one player scores how many goals in a game?", "3", "2", "4", "5"),
    _q("sports", 3, "Usain Bolt set world records in which events?", "Sprinting (100m and 200m)", "Marathon", "Long jump", "Hurdles"),
    _q("sports", 1, "In hide and seek, what does the seeker do first?", "Counts with eyes closed", "Runs away", "Hides", "Shouts the winner"),
    _q("sports", 2, "Which sport do the Harlem Globetrotters play?", "Basketball", "Baseball", "Soccer", "Hockey"),
    _q("sports", 3, "In golf, what is one stroke under par on a hole called?", "A birdie", "An eagle", "A bogey", "An albatross"),
    _q("sports", 3, "Which chess piece is the most powerful?", "The queen", "The king", "The rook", "The bishop"),

    # ================= HISTORY =================
    _q("history", 1, "Who was the first President of the United States?", "George Washington", "Abraham Lincoln", "Thomas Jefferson", "John Adams"),
    _q("history", 1, "Which ancient Egyptian buildings are giant triangles made of stone?", "The pyramids", "The castles", "The cathedrals", "The lighthouses"),
    _q("history", 1, "Knights in the Middle Ages wore what to protect themselves?", "Armor", "Raincoats", "Leather aprons", "Wool blankets"),
    _q("history", 1, "What did people use to write before pens and pencils — dipped in ink?", "Feather quills", "Crayons", "Chalk only", "Markers"),
    _q("history", 1, "Which giant animals with tusks lived in the Ice Age and are now extinct?", "Woolly mammoths", "Giraffes", "Hippos", "Camels"),
    _q("history", 1, "Who sailed the ocean blue in 1492?", "Christopher Columbus", "Ferdinand Magellan", "Marco Polo", "Captain Cook"),
    _q("history", 1, "Castles were built with a big ditch of water around them called a what?", "Moat", "Pool", "Canal", "Pond"),
    _q("history", 1, "The Pilgrims sailed to America on which ship?", "The Mayflower", "The Titanic", "The Santa Maria", "The Endeavour"),
    _q("history", 1, "Which country's kings and queens live in Buckingham Palace?", "England", "France", "Spain", "Denmark"),
    _q("history", 1, "Cavemen made paintings on the walls of what?", "Caves", "Castles", "Ships", "Tents"),
    _q("history", 1, "What did pirates traditionally search for, marked by an X on a map?", "Treasure", "Fish", "New ships", "Islands to farm"),
    _q("history", 1, "Which president is on the U.S. one-dollar bill?", "George Washington", "Abraham Lincoln", "Benjamin Franklin", "Thomas Jefferson"),
    _q("history", 2, "Who was the U.S. president during most of the Civil War?", "Abraham Lincoln", "George Washington", "Ulysses S. Grant", "Andrew Jackson"),
    _q("history", 2, "In which year did the United States declare independence?", "1776", "1789", "1812", "1750"),
    _q("history", 2, "The ancient Romans spoke which language?", "Latin", "Greek", "Italian", "Spanish"),
    _q("history", 2, "Who was the famous queen of ancient Egypt, the last of her dynasty?", "Cleopatra", "Nefertiti", "Hatshepsut", "Isis"),
    _q("history", 2, "What wonder of the world did the ancient Egyptians build at Giza?", "The Great Pyramid", "The Colosseum", "The Parthenon", "Stonehenge"),
    _q("history", 2, "Which ship famously sank in 1912 after hitting an iceberg?", "The Titanic", "The Lusitania", "The Britannic", "The Queen Mary"),
    _q("history", 2, "Who was the first person to walk on the moon?", "Neil Armstrong", "Buzz Aldrin", "John Glenn", "Yuri Gagarin"),
    _q("history", 2, "The gladiators of ancient Rome fought in which famous arena?", "The Colosseum", "The Parthenon", "The Forum", "The Circus Tent"),
    _q("history", 2, "Which civilization built Machu Picchu?", "The Inca", "The Maya", "The Aztec", "The Olmec"),
    _q("history", 2, "Who invented the telephone?", "Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Samuel Morse"),
    _q("history", 2, "Which country gave the world the samurai?", "Japan", "China", "Mongolia", "Korea"),
    _q("history", 2, "George Washington is said to have chopped down which kind of tree in legend?", "A cherry tree", "An apple tree", "An oak tree", "A maple tree"),
    _q("history", 2, "The Wright brothers are famous for the first successful what?", "Airplane flight", "Car", "Steamboat", "Train"),
    _q("history", 2, "Which wall divided a German city until 1989?", "The Berlin Wall", "The Great Wall", "Hadrian's Wall", "The Western Wall"),
    _q("history", 2, "Vikings came from which part of the world?", "Scandinavia", "The Mediterranean", "North Africa", "East Asia"),
    _q("history", 2, "Who wrote the Declaration of Independence's first draft?", "Thomas Jefferson", "George Washington", "Benjamin Franklin", "John Hancock"),
    _q("history", 2, "Which explorer's expedition was the first to sail around the world?", "Ferdinand Magellan's", "Christopher Columbus's", "Marco Polo's", "Vasco da Gama's"),
    _q("history", 2, "Martin Luther King Jr. is famous for which speech?", "I Have a Dream", "The Gettysburg Address", "Give Me Liberty", "Four Freedoms"),
    _q("history", 2, "The Statue of Liberty stands in the harbor of which city?", "New York", "Boston", "Philadelphia", "Washington, D.C."),
    _q("history", 2, "In which country did the Olympic Games begin?", "Greece", "Rome", "Egypt", "France"),
    _q("history", 2, "Which famous scientist developed the theory of relativity?", "Albert Einstein", "Isaac Newton", "Galileo", "Stephen Hawking"),
    _q("history", 2, "Who was the young French heroine who led armies and was later made a saint?", "Joan of Arc", "Marie Antoinette", "Catherine the Great", "Queen Victoria"),
    _q("history", 2, "The Liberty Bell is located in which U.S. city?", "Philadelphia", "Boston", "Washington, D.C.", "New York"),
    _q("history", 3, "Which empire was ruled by Julius Caesar?", "The Roman Empire", "The Greek Empire", "The Persian Empire", "The Ottoman Empire"),
    _q("history", 3, "In which year did World War II end?", "1945", "1939", "1941", "1950"),
    _q("history", 3, "Who painted the ceiling of the Sistine Chapel?", "Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"),
    _q("history", 3, "The Magna Carta was signed in which country?", "England", "France", "Spain", "Italy"),
    _q("history", 3, "Which U.S. president delivered the Gettysburg Address?", "Abraham Lincoln", "George Washington", "Theodore Roosevelt", "Thomas Jefferson"),
    _q("history", 3, "Who was the Macedonian king who conquered a vast empire by age 30?", "Alexander the Great", "Julius Caesar", "Hannibal", "King Xerxes"),
    _q("history", 3, "The Renaissance began in which country?", "Italy", "France", "England", "Germany"),
    _q("history", 3, "Which ancient city was buried by the eruption of Mount Vesuvius?", "Pompeii", "Athens", "Carthage", "Troy"),
    _q("history", 3, "Who invented the printing press with movable type in Europe?", "Johannes Gutenberg", "Leonardo da Vinci", "Benjamin Franklin", "Galileo"),
    _q("history", 3, "The first Thanksgiving in America is associated with which colony?", "Plymouth", "Jamestown", "Roanoke", "Salem"),
    _q("history", 3, "Which queen ruled England for over 63 years starting in 1837?", "Queen Victoria", "Queen Elizabeth I", "Queen Mary", "Queen Anne"),
    _q("history", 3, "The Cold War was mainly between the USA and which country?", "The Soviet Union", "China", "Germany", "Japan"),
    _q("history", 3, "Which document begins 'We the People'?", "The U.S. Constitution", "The Declaration of Independence", "The Bill of Rights", "The Gettysburg Address"),
    _q("history", 3, "Genghis Khan founded which empire?", "The Mongol Empire", "The Ottoman Empire", "The Persian Empire", "The Ming Dynasty"),
    _q("history", 3, "Who was the British Prime Minister for most of World War II?", "Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Margaret Thatcher"),
    _q("history", 3, "The ancient Greeks left a giant wooden gift outside which city?", "Troy", "Sparta", "Athens", "Olympia"),
    _q("history", 3, "Which U.S. purchase of 1803 doubled the size of the country?", "The Louisiana Purchase", "The Alaska Purchase", "The Gadsden Purchase", "The Florida Purchase"),
    _q("history", 3, "Marie Curie won Nobel Prizes in which two fields?", "Physics and Chemistry", "Medicine and Peace", "Chemistry and Literature", "Physics and Medicine"),
    _q("history", 3, "Which pharaoh's nearly untouched tomb was discovered in 1922?", "Tutankhamun", "Ramses II", "Khufu", "Akhenaten"),
    _q("history", 3, "The Hundred Years' War was fought mainly between which two countries?", "England and France", "Spain and Portugal", "Rome and Carthage", "Germany and Russia"),
    _q("history", 1, "Long ago, before cars, people rode what to travel?", "Horses", "Skateboards", "Scooters", "Rollerblades"),
    _q("history", 1, "Dinosaur bones that turned to stone are called what?", "Fossils", "Crystals", "Pebbles", "Statues"),
    _q("history", 2, "Which famous nurse founded modern nursing and was called 'the Lady with the Lamp'?", "Florence Nightingale", "Clara Barton", "Mother Teresa", "Marie Curie"),
    _q("history", 2, "The Aztecs built their capital in which modern-day country?", "Mexico", "Peru", "Spain", "Guatemala"),
    _q("history", 2, "Which U.S. president appears on Mount Rushmore along with Washington, Jefferson, and Lincoln?", "Theodore Roosevelt", "Franklin Roosevelt", "John Adams", "Andrew Jackson"),
    _q("history", 3, "Which war was fought between the North and South of the United States?", "The Civil War", "The Revolutionary War", "The War of 1812", "The French and Indian War"),
    _q("history", 3, "Anne Frank became famous for writing what while in hiding?", "A diary", "A song", "A play", "Letters to a president"),

    # ================= FOOD & DRINK =================
    _q("food", 1, "What food do you get from chickens for breakfast?", "Eggs", "Milk", "Cheese", "Honey"),
    _q("food", 1, "Which fruit is yellow, curved, and peeled by monkeys and kids alike?", "Banana", "Apple", "Orange", "Grape"),
    _q("food", 1, "What is pizza usually topped with besides sauce?", "Cheese", "Ice cream", "Cereal", "Jelly"),
    _q("food", 1, "Which drink comes from cows?", "Milk", "Juice", "Soda", "Lemonade"),
    _q("food", 1, "What do you spread on bread with jelly in a classic sandwich?", "Peanut butter", "Ketchup", "Mustard", "Mayonnaise"),
    _q("food", 1, "Which vegetable do rabbits famously love?", "Carrots", "Potatoes", "Onions", "Peppers"),
    _q("food", 1, "What frozen treat comes in a cone?", "Ice cream", "Soup", "Pudding", "Yogurt drink"),
    _q("food", 1, "Which fruit keeps the doctor away, one a day?", "Apple", "Banana", "Cherry", "Peach"),
    _q("food", 1, "Popcorn is made from which food?", "Corn", "Rice", "Wheat", "Beans"),
    _q("food", 1, "What shape is a slice of pizza usually?", "Triangle", "Square", "Circle", "Star"),
    _q("food", 1, "Which meal do most people eat in the morning?", "Breakfast", "Dinner", "Supper", "Dessert"),
    _q("food", 1, "What do bees make that we spread on toast?", "Honey", "Butter", "Jam", "Syrup"),
    _q("food", 1, "French fries are made from which vegetable?", "Potatoes", "Carrots", "Corn", "Zucchini"),
    _q("food", 1, "Which fruit is red, has seeds on the OUTSIDE, and tops shortcake?", "Strawberry", "Raspberry", "Cherry", "Apple"),
    _q("food", 2, "Which country is famous for inventing pizza?", "Italy", "France", "Greece", "Spain"),
    _q("food", 2, "What is the main ingredient in guacamole?", "Avocado", "Tomato", "Pea", "Cucumber"),
    _q("food", 2, "Sushi originally comes from which country?", "Japan", "China", "Thailand", "Korea"),
    _q("food", 2, "What are raisins before they are dried?", "Grapes", "Plums", "Cherries", "Cranberries"),
    _q("food", 2, "Which spice comes from the bark of a tree and flavors rolls and toast?", "Cinnamon", "Pepper", "Ginger", "Nutmeg"),
    _q("food", 2, "Tacos and burritos come from which country's cuisine?", "Mexico", "Spain", "Brazil", "Cuba"),
    _q("food", 2, "What is the main ingredient of an omelet?", "Eggs", "Flour", "Cheese", "Potatoes"),
    _q("food", 2, "Which fruit is known for having lots of vitamin C and shares its name with a color?", "Orange", "Banana", "Kiwi", "Mango"),
    _q("food", 2, "Bread rises because of which ingredient?", "Yeast", "Salt", "Sugar", "Butter"),
    _q("food", 2, "What is a pickle before it is pickled?", "A cucumber", "A zucchini", "A green pepper", "A squash"),
    _q("food", 2, "Which pasta shape is long, thin, and round like string?", "Spaghetti", "Penne", "Macaroni", "Lasagna"),
    _q("food", 2, "Maple syrup comes from what?", "Tree sap", "Bee hives", "Sugar cane only", "Corn stalks"),
    _q("food", 2, "Which country gave us croissants and baguettes?", "France", "Italy", "Germany", "Belgium"),
    _q("food", 2, "What vegetable makes you cry when you chop it?", "Onion", "Carrot", "Celery", "Lettuce"),
    _q("food", 2, "Ketchup is mostly made from which fruit?", "Tomatoes", "Red peppers", "Beets", "Cherries"),
    _q("food", 2, "Which dairy product is churned from cream?", "Butter", "Yogurt", "Cottage cheese", "Whipped milk"),
    _q("food", 2, "What grain is used to make most breakfast oatmeal?", "Oats", "Rice", "Corn", "Barley"),
    _q("food", 2, "A hamburger patty is traditionally made from which meat?", "Beef", "Ham", "Chicken", "Turkey"),
    _q("food", 2, "Which nut is used to make marzipan?", "Almond", "Peanut", "Cashew", "Walnut"),
    _q("food", 2, "Which Italian dessert's name means 'pick me up'?", "Tiramisu", "Cannoli", "Gelato", "Panna cotta"),
    _q("food", 2, "Which drink is made by steeping leaves in hot water?", "Tea", "Coffee", "Hot chocolate", "Cider"),
    _q("food", 2, "Guacamole, salsa, and tortilla chips are staples of which cuisine?", "Mexican", "Italian", "Greek", "Chinese"),
    _q("food", 3, "What is the main ingredient in traditional hummus?", "Chickpeas", "Lentils", "Black beans", "Peas"),
    _q("food", 3, "Which cheese is traditionally used on top of pizza Margherita?", "Mozzarella", "Cheddar", "Parmesan", "Swiss"),
    _q("food", 3, "Which vitamin are oranges most famous for?", "Vitamin C", "Vitamin A", "Vitamin D", "Vitamin K"),
    _q("food", 3, "What type of food is a portobello?", "A mushroom", "A pepper", "A fish", "A cheese"),
    _q("food", 3, "Which country is famous for its 'afternoon tea' tradition with scones and finger sandwiches?", "England", "USA", "France", "Brazil"),
    _q("food", 3, "Chocolate is made from the beans of which tree?", "Cacao", "Coffee", "Vanilla", "Palm"),
    _q("food", 3, "What is the world's most expensive spice by weight, made from crocus flowers?", "Saffron", "Vanilla", "Cardamom", "Truffle salt"),
    _q("food", 3, "Which fish is traditionally used in fish and chips?", "Cod", "Salmon", "Tuna", "Trout"),
    _q("food", 3, "What is tofu made from?", "Soybeans", "Rice", "Wheat", "Almonds"),
    _q("food", 3, "Paella is a famous rice dish from which country?", "Spain", "Italy", "Portugal", "Mexico"),
    _q("food", 3, "Which fruit is dried to make prunes?", "Plums", "Grapes", "Apricots", "Figs"),
    _q("food", 3, "What gives red velvet cake its classic tang?", "Buttermilk", "Lemon juice", "Orange zest", "Sour candy"),
    _q("food", 3, "Which herb is the main ingredient in pesto?", "Basil", "Parsley", "Cilantro", "Mint"),
    _q("food", 3, "Croissants are famous from France, but what shape are they?", "Crescent", "Ring", "Braid", "Knot"),
    _q("food", 3, "Which root is ginger ale flavored with?", "Ginger", "Turmeric", "Horseradish", "Beet"),
    _q("food", 3, "What kind of pastry are eclairs made from?", "Choux pastry", "Puff pastry", "Shortcrust", "Filo"),
    _q("food", 3, "Which state is famous for growing most of America's pineapples historically?", "Hawaii", "Florida", "California", "Texas"),
    _q("food", 3, "Mozzarella was traditionally made from the milk of which animal?", "Water buffalo", "Goat", "Sheep", "Camel"),
    _q("food", 3, "What is the primary ingredient in traditional Japanese miso soup base?", "Fermented soybean paste", "Fish eggs", "Seaweed only", "Rice vinegar"),
    _q("food", 3, "A calzone is essentially a folded what?", "Pizza", "Sandwich", "Pancake", "Taco"),
    _q("food", 1, "What do you pour on pancakes?", "Syrup", "Gravy", "Salsa", "Soy sauce"),
    _q("food", 1, "Which food is twisted, salty, and brown?", "A pretzel", "A pancake", "A muffin", "A bagel"),
    _q("food", 2, "Which drink do the British famously pair with scones?", "Tea", "Coffee", "Lemonade", "Root beer"),
    _q("food", 2, "What is the green fruit with a big pit that goes on toast?", "Avocado", "Kiwi", "Lime", "Green apple"),
    _q("food", 3, "Which cheese has famous blue veins running through it?", "Blue cheese", "Cheddar", "Brie", "Provolone"),
    _q("food", 3, "Which grain is sushi rice made from?", "Rice", "Wheat", "Barley", "Quinoa"),

    # ================= ANIMALS =================
    _q("animals", 1, "Which animal says 'moo'?", "Cow", "Pig", "Duck", "Horse"),
    _q("animals", 1, "What is the tallest animal in the world?", "Giraffe", "Elephant", "Horse", "Camel"),
    _q("animals", 1, "Which animal is known as man's best friend?", "Dog", "Cat", "Horse", "Parrot"),
    _q("animals", 1, "What do pandas mostly eat?", "Bamboo", "Fish", "Meat", "Berries"),
    _q("animals", 1, "Which bird cannot fly but runs very fast?", "Ostrich", "Eagle", "Parrot", "Owl"),
    _q("animals", 1, "What is a baby cat called?", "Kitten", "Puppy", "Cub", "Chick"),
    _q("animals", 1, "Which animal has a long trunk?", "Elephant", "Rhino", "Hippo", "Giraffe"),
    _q("animals", 1, "What do you call a baby frog with a tail that swims?", "Tadpole", "Minnow", "Larva", "Froglet"),
    _q("animals", 1, "Which animal hops and keeps its baby in a pouch?", "Kangaroo", "Rabbit", "Frog", "Squirrel"),
    _q("animals", 1, "What color are zebras' stripes?", "Black and white", "Brown and white", "Black and orange", "Gray and black"),
    _q("animals", 1, "Which sea creature has eight arms?", "Octopus", "Starfish", "Crab", "Jellyfish"),
    _q("animals", 1, "What do cats say?", "Meow", "Woof", "Oink", "Quack"),
    _q("animals", 1, "Which animal is the king of the jungle?", "Lion", "Tiger", "Elephant", "Gorilla"),
    _q("animals", 1, "Which black and white bird waddles on ice?", "Penguin", "Duck", "Seagull", "Puffin"),
    _q("animals", 1, "What do caterpillars eat mostly?", "Leaves", "Fish", "Seeds", "Honey"),
    _q("animals", 2, "What is the largest animal that has ever lived?", "Blue whale", "African elephant", "T-Rex", "Giant squid"),
    _q("animals", 2, "How many legs does a spider have?", "8", "6", "10", "12"),
    _q("animals", 2, "Which animal is the fastest on land?", "Cheetah", "Lion", "Horse", "Greyhound"),
    _q("animals", 2, "What do you call a group of wolves?", "A pack", "A herd", "A flock", "A school"),
    _q("animals", 2, "Which bird is a symbol of the United States?", "Bald eagle", "Hawk", "Falcon", "Condor"),
    _q("animals", 2, "What is a baby kangaroo called?", "A joey", "A cub", "A calf", "A kit"),
    _q("animals", 2, "Which animal sleeps upside down hanging from its feet?", "Bat", "Owl", "Sloth", "Koala"),
    _q("animals", 2, "How do dolphins breathe?", "Through a blowhole", "Through gills", "Through their skin", "They don't need air"),
    _q("animals", 2, "Which animal changes color to blend in with its surroundings?", "Chameleon", "Iguana", "Gecko", "Salamander"),
    _q("animals", 2, "What is the only mammal that can truly fly?", "Bat", "Flying squirrel", "Sugar glider", "Ostrich"),
    _q("animals", 2, "Which big cat has stripes?", "Tiger", "Leopard", "Cheetah", "Jaguar"),
    _q("animals", 2, "What do camels store in their humps?", "Fat", "Water", "Food", "Air"),
    _q("animals", 2, "Which animal builds dams in rivers?", "Beaver", "Otter", "Muskrat", "Raccoon"),
    _q("animals", 2, "How many hearts does an octopus have?", "3", "1", "2", "8"),
    _q("animals", 2, "What is a group of fish called?", "A school", "A pack", "A herd", "A gaggle"),
    _q("animals", 2, "Which bird can mimic human speech?", "Parrot", "Eagle", "Penguin", "Flamingo"),
    _q("animals", 2, "Where do polar bears live in the wild?", "The Arctic", "Antarctica", "Alaska's forests only", "Greenland's cities"),
    _q("animals", 2, "What do owls mostly hunt at night?", "Small rodents", "Fish", "Berries", "Insects only"),
    _q("animals", 2, "Which slow animal carries its home on its back?", "Snail", "Slug", "Worm", "Caterpillar"),
    _q("animals", 2, "What is a female deer called?", "A doe", "A fawn", "A mare", "A ewe"),
    _q("animals", 2, "Which African animal has a horn on its nose?", "Rhinoceros", "Hippopotamus", "Elephant", "Buffalo"),
    _q("animals", 2, "Why do flamingos turn pink?", "From the food they eat", "From the sun", "They are born pink", "From cold water"),
    _q("animals", 2, "Which insect makes honey?", "Bee", "Wasp", "Ant", "Butterfly"),
    _q("animals", 2, "What is the biggest species of bear?", "Polar bear", "Grizzly bear", "Black bear", "Panda"),
    _q("animals", 3, "How many stomach chambers does a cow have?", "4", "1", "2", "3"),
    _q("animals", 3, "Which animal has the longest lifespan among these?", "Giant tortoise", "Elephant", "Parrot", "Whale shark"),
    _q("animals", 3, "What is the fastest bird in a dive?", "Peregrine falcon", "Golden eagle", "Ostrich", "Swift"),
    _q("animals", 3, "Which animal's fingerprints are so similar to humans' they can confuse investigators?", "Koala", "Chimpanzee", "Gorilla", "Raccoon"),
    _q("animals", 3, "What is a group of owls called?", "A parliament", "A murder", "A colony", "A convocation of eagles"),
    _q("animals", 3, "Which large ape shares the most DNA with humans?", "Chimpanzee", "Gorilla", "Orangutan", "Baboon"),
    _q("animals", 3, "What is the largest living reptile?", "Saltwater crocodile", "Komodo dragon", "Anaconda", "Galapagos tortoise"),
    _q("animals", 3, "Which animal never stops growing teeth, replacing them constantly?", "Shark", "Lion", "Horse", "Wolf"),
    _q("animals", 3, "What is the only continent where giraffes live in the wild?", "Africa", "Asia", "South America", "Australia"),
    _q("animals", 3, "Which bird lays the largest egg?", "Ostrich", "Emu", "Eagle", "Swan"),
    _q("animals", 3, "How do snakes smell?", "With their tongue", "With their nose only", "With their eyes", "Through their skin"),
    _q("animals", 3, "What is a male chicken called?", "A rooster", "A drake", "A gander", "A tom"),
    _q("animals", 3, "Which sea creature is known for having three hearts and blue blood?", "Octopus", "Shark", "Dolphin", "Sea turtle"),
    _q("animals", 3, "Emperor penguins live on which continent?", "Antarctica", "The Arctic", "Australia", "South America"),
    _q("animals", 3, "What do you call an animal active mainly at night?", "Nocturnal", "Diurnal", "Hibernal", "Migratory"),
    _q("animals", 3, "Which whale has a long spiral tusk, like a unicorn of the sea?", "Narwhal", "Beluga", "Orca", "Humpback"),
    _q("animals", 3, "What is the process called when bears sleep through winter?", "Hibernation", "Migration", "Metamorphosis", "Camouflage"),
    _q("animals", 3, "Which insect can lift many times its own body weight?", "Ant", "Fly", "Mosquito", "Moth"),
    _q("animals", 3, "What is the largest species of big cat?", "Tiger", "Lion", "Jaguar", "Leopard"),
    _q("animals", 3, "Which dog breed is famous for rescuing people in the Swiss Alps?", "Saint Bernard", "German Shepherd", "Husky", "Great Dane"),
    _q("animals", 1, "Which animal barks?", "Dog", "Cat", "Fish", "Rabbit"),
    _q("animals", 2, "What is a baby sheep called?", "A lamb", "A calf", "A kid", "A foal"),
    _q("animals", 3, "Which animal is the largest land animal alive today?", "African elephant", "Giraffe", "Hippopotamus", "White rhinoceros"),

    # ================= KIDS ZONE =================
    _q("kids", 1, "What color is the sky on a clear sunny day?", "Blue", "Green", "Purple", "Orange"),
    _q("kids", 1, "How many legs does a dog have?", "4", "2", "6", "8"),
    _q("kids", 1, "What sound does a duck make?", "Quack", "Moo", "Baa", "Neigh"),
    _q("kids", 1, "What do you wear on your feet?", "Shoes", "Hats", "Gloves", "Scarves"),
    _q("kids", 1, "Which fruit is red and crunchy and grows on trees?", "Apple", "Banana", "Grape", "Lemon"),
    _q("kids", 1, "What color is grass?", "Green", "Blue", "Red", "Yellow"),
    _q("kids", 1, "How many eyes do you have?", "2", "1", "3", "4"),
    _q("kids", 1, "What do you use to brush your teeth?", "A toothbrush", "A hairbrush", "A spoon", "A comb"),
    _q("kids", 1, "Which animal is big, gray, and loves peanuts in cartoons?", "Elephant", "Mouse", "Cat", "Fish"),
    _q("kids", 1, "What do you sleep in at night?", "A bed", "A bathtub", "A closet", "A car"),
    _q("kids", 1, "What shape is a ball?", "Round", "Square", "Triangle", "Flat"),
    _q("kids", 1, "Which of these can fly?", "A bird", "A fish", "A dog", "A turtle"),
    _q("kids", 1, "What do cows drink when they are babies?", "Milk", "Juice", "Soda", "Tea"),
    _q("kids", 1, "What color is a banana when it is ripe?", "Yellow", "Blue", "Red", "Purple"),
    _q("kids", 1, "How many fingers are on one hand (counting the thumb)?", "5", "4", "6", "10"),
    _q("kids", 1, "What do you call the star that lights up our day?", "The Sun", "The Moon", "Mars", "A comet"),
    _q("kids", 1, "Which vehicle has two wheels and pedals?", "A bicycle", "A car", "A boat", "A train"),
    _q("kids", 1, "What do fish live in?", "Water", "Trees", "Caves", "Nests"),
    _q("kids", 1, "Which season is the coldest with snow?", "Winter", "Summer", "Spring", "Fall"),
    _q("kids", 1, "What do you put on a birthday cake and blow out?", "Candles", "Balloons", "Ribbons", "Stickers"),
    _q("kids", 1, "Which animal has a very long neck?", "Giraffe", "Pig", "Dog", "Duck"),
    _q("kids", 1, "What color are most fire trucks?", "Red", "Blue", "Green", "Pink"),
    _q("kids", 1, "What do chickens lay?", "Eggs", "Seeds", "Stones", "Apples"),
    _q("kids", 1, "Where does a bird lay its eggs?", "In a nest", "In a cave", "Underwater", "In a burrow"),
    _q("kids", 1, "What do you call frozen rain that falls as white flakes?", "Snow", "Rain", "Fog", "Mist"),
    _q("kids", 1, "Which meal comes at the end of the day?", "Dinner", "Breakfast", "Brunch", "Snack time"),
    _q("kids", 1, "What is the opposite of hot?", "Cold", "Warm", "Wet", "Soft"),
    _q("kids", 1, "What is the opposite of big?", "Small", "Tall", "Wide", "Heavy"),
    _q("kids", 1, "Which animal purrs and chases mice?", "Cat", "Dog", "Rabbit", "Bird"),
    _q("kids", 1, "How many wheels does a car have?", "4", "2", "3", "6"),
    _q("kids", 1, "What do you use to color pictures?", "Crayons", "Forks", "Keys", "Rocks"),
    _q("kids", 1, "Which one lives in the ocean?", "A shark", "A lion", "A cow", "A chicken"),
    _q("kids", 1, "What do plants grow from?", "Seeds", "Rocks", "Sand", "Coins"),
    _q("kids", 1, "What is the first letter of the alphabet?", "A", "B", "Z", "C"),
    _q("kids", 1, "Which shape has three sides?", "Triangle", "Square", "Circle", "Rectangle"),
    _q("kids", 1, "What sound does a cat make?", "Meow", "Woof", "Moo", "Roar"),
    _q("kids", 1, "What do you wear when it rains?", "A raincoat", "A swimsuit", "Pajamas", "Sunglasses"),
    _q("kids", 1, "Which animal says 'oink'?", "Pig", "Sheep", "Cow", "Hen"),
    _q("kids", 1, "What color is an orange fruit?", "Orange", "Blue", "Green", "Purple"),
    _q("kids", 1, "Where do you go to learn with teachers?", "School", "The beach", "The kitchen", "The garage"),
    _q("kids", 1, "How many ears do you have?", "2", "1", "3", "4"),
    _q("kids", 1, "What melts in the sun?", "Ice cream", "Rocks", "Metal spoons", "Shoes"),
    _q("kids", 1, "Which fruit do monkeys love in cartoons?", "Bananas", "Pineapples", "Cherries", "Melons"),
    _q("kids", 1, "What do you say when someone gives you a present?", "Thank you", "Goodbye", "Excuse me", "Good night"),
    _q("kids", 1, "Which animal hops and has long ears?", "Rabbit", "Turtle", "Snake", "Fish"),
    _q("kids", 1, "What do firefighters use to spray water?", "A hose", "A broom", "A ladder only", "A bucket only"),
    _q("kids", 1, "What is the opposite of up?", "Down", "Over", "Around", "Beside"),
    _q("kids", 1, "What twinkles in the night sky?", "Stars", "Rocks", "Clouds", "Rainbows"),
    _q("kids", 1, "Which farm animal gives us wool?", "Sheep", "Cow", "Chicken", "Pig"),
    _q("kids", 1, "What do you use to cut paper?", "Scissors", "A spoon", "A pillow", "A crayon"),
    _q("kids", 1, "Which little insect flashes light at night?", "Firefly", "Ant", "Beetle", "Worm"),
    _q("kids", 1, "What color do you get when you mix red and yellow?", "Orange", "Green", "Purple", "Brown"),
    _q("kids", 1, "Which animal slowly carries its shell home everywhere?", "Turtle", "Puppy", "Kitten", "Pony"),
    _q("kids", 1, "What do you drink from at a water fountain?", "Water", "Milk", "Juice", "Soup"),
    _q("kids", 1, "How many sides does a square have?", "4", "3", "5", "6"),
    _q("kids", 1, "Which one is a vegetable?", "Broccoli", "Cookie", "Cupcake", "Candy"),
    _q("kids", 1, "What do you call your mom's mom?", "Grandma", "Aunt", "Sister", "Cousin"),
    _q("kids", 1, "What does a red traffic light mean?", "Stop", "Go", "Go faster", "Turn around"),
    _q("kids", 1, "Which tool tells you how heavy something is?", "A scale", "A clock", "A ruler", "A cup"),
    _q("kids", 1, "What do ducks love to splash in?", "Water", "Sand", "Leaves", "Snow"),
]


# ---------------- helpers ----------------

def norm(s):
    """Normalized question text — the dedupe/no-repeat key."""
    s = unicodedata.normalize("NFKD", str(s).lower())
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = re.sub(r"[^a-z0-9]+", " ", s)
    return " ".join(s.split())


def key(entry):
    return norm(entry["q"])


CAT_SLUGS = [slug for slug, _, _ in CATEGORIES]


def categories():
    """Category metadata for the lobby picker (no questions)."""
    counts = {slug: 0 for slug in CAT_SLUGS}
    fam = {slug: 0 for slug in CAT_SLUGS}
    for e in BANK:
        counts[e["cat"]] += 1
        if e["diff"] <= 2:
            fam[e["cat"]] += 1
    return [{"slug": slug, "title": title, "icon": icon,
             "count": counts[slug], "family_count": fam[slug]}
            for slug, title, icon in CATEGORIES]


def draw(n, rng, cat="mixed", family=True, exclude=()):
    """Draw `n` distinct questions, seeded by `rng`, never repeating within
    the result and avoiding `exclude` keys (recently played) while enough
    fresh material remains.

    family=True restricts to diff 1-2, weighted toward diff 1 (2:1) so the
    youngest player stays in the game. cat="mixed" uses the whole bank.
    """
    pool = [e for e in BANK if cat in ("mixed", e["cat"])]
    if family:
        pool = [e for e in pool if e["diff"] <= 2]
        weighted = pool + [e for e in pool if e["diff"] == 1]
    else:
        weighted = list(pool)
    rng.shuffle(weighted)
    exclude = set(exclude)
    picked, seen = [], set()
    for e in weighted:
        k = key(e)
        if k in seen or k in exclude:
            continue
        seen.add(k)
        picked.append(e)
        if len(picked) >= n:
            return picked
    # not enough fresh questions: allow recently played ones back in
    for e in weighted:
        k = key(e)
        if k in seen:
            continue
        seen.add(k)
        picked.append(e)
        if len(picked) >= n:
            break
    return picked


