"""Charades decks — the content IS the game, so these are curated by hand.

Item format: "Display Name|alias|alias..." — the first segment is shown to
the actor; every segment is an accepted answer (all matching happens on
normalized text, so punctuation/case/"the" don't matter — aliases are only
needed for genuinely different wordings).

Curation rules: actable with a body and zero props, known across three
generations of one family, no duplicates, nothing that only works written
down. Difficulty is per-deck ("easy" plays with kids, "hard" is grown-up
night)."""

import re
import unicodedata


def norm(s):
    """The one normalization every match goes through: lowercase, accents
    stripped, punctuation dropped, leading articles dropped, spaces removed."""
    s = unicodedata.normalize("NFKD", str(s).lower())
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = re.sub(r"[^a-z0-9 ]", " ", s)
    words = s.split()
    while words and words[0] in ("the", "a", "an"):
        words = words[1:]
    return "".join(words)


DECKS = {
    "mix": {
        "title": "EVERYTHING",
        "icon": "🎲",
        "blurb": "Every deck shuffled together — the full buffet.",
        "difficulty": "medium",
        "items": [],   # filled below from all other decks
    },
    "animals": {
        "title": "ANIMALS",
        "icon": "🦁",
        "blurb": "Creatures great, small, and extremely actable.",
        "difficulty": "easy",
        "items": [
            "Elephant", "Giraffe", "Kangaroo", "Penguin", "Monkey", "Gorilla",
            "Lion", "Tiger", "Bear", "Snake", "Eagle", "Owl", "Chicken",
            "Rooster", "Duck", "Swan", "Flamingo", "Ostrich", "Peacock",
            "Cat", "Dog", "Puppy", "Kitten", "Horse", "Donkey", "Zebra",
            "Cow", "Bull", "Goat", "Sheep", "Pig", "Rabbit", "Squirrel",
            "Chipmunk", "Mouse", "Rat", "Hamster", "Hedgehog", "Skunk",
            "Raccoon", "Fox", "Wolf", "Deer", "Moose", "Buffalo", "Camel",
            "Hippo|hippopotamus", "Rhino|rhinoceros", "Crocodile", "Alligator",
            "Turtle", "Tortoise", "Frog", "Toad", "Lizard", "Chameleon",
            "Iguana", "Gecko", "Shark", "Whale", "Dolphin", "Octopus",
            "Squid", "Jellyfish", "Starfish", "Crab", "Lobster", "Shrimp",
            "Clam", "Seahorse", "Stingray", "Eel", "Piranha", "Goldfish",
            "Salmon", "Catfish", "Swordfish", "Seal", "Sea lion", "Walrus",
            "Otter", "Beaver", "Platypus", "Koala", "Sloth", "Anteater",
            "Armadillo", "Porcupine", "Bat", "Mole", "Ferret", "Meerkat",
            "Lemur", "Chimpanzee|chimp", "Orangutan", "Baboon", "Panda",
            "Polar bear", "Grizzly bear", "Cheetah", "Leopard", "Jaguar",
            "Panther", "Cougar|mountain lion", "Hyena", "Jackal", "Bee",
            "Wasp", "Butterfly", "Caterpillar", "Spider", "Scorpion", "Ant",
            "Grasshopper", "Cricket", "Ladybug", "Dragonfly", "Firefly",
            "Mosquito", "Fly", "Worm", "Snail", "Slug", "Centipede",
            "Praying mantis", "Moth", "Turkey", "Goose", "Pigeon", "Crow",
            "Parrot", "Woodpecker", "Hummingbird", "Pelican", "Seagull",
            "Vulture", "Hawk", "Falcon", "Bald eagle", "Dodo", "T-Rex|trex|tyrannosaurus|tyrannosaurus rex",
            "Velociraptor|raptor", "Pterodactyl", "Dinosaur", "Dragon",
            "Unicorn", "Mermaid", "Bigfoot|sasquatch", "Loch Ness Monster|nessie",
        ],
    },
    "actions": {
        "title": "ACTIONS",
        "icon": "🏃",
        "blurb": "Everyday things people do — the classic charades fuel.",
        "difficulty": "easy",
        "items": [
            "Brushing teeth", "Washing hair", "Taking a shower", "Shaving",
            "Putting on makeup", "Getting dressed", "Tying shoelaces|tying shoes",
            "Ironing a shirt|ironing", "Folding laundry", "Vacuuming",
            "Sweeping the floor|sweeping", "Mopping", "Washing dishes",
            "Cooking dinner|cooking", "Flipping pancakes", "Cracking an egg",
            "Chopping onions|cutting onions", "Grating cheese", "Stirring soup",
            "Setting the table", "Eating spaghetti", "Eating corn on the cob",
            "Eating a taco", "Licking an ice cream cone|eating ice cream",
            "Drinking coffee", "Blowing on hot soup", "Opening a jar",
            "Opening a present", "Wrapping a gift|wrapping a present",
            "Blowing out candles", "Making a wish", "Baking cookies",
            "Rolling dough", "Making a sandwich", "Peeling a banana",
            "Squeezing a lemon", "Flossing", "Gargling", "Blowing your nose",
            "Sneezing", "Yawning", "Snoring", "Sleepwalking", "Waking up",
            "Hitting the snooze button", "Stretching", "Jumping jacks",
            "Push-ups|pushups", "Sit-ups|situps", "Lifting weights",
            "Jumping rope|jump rope", "Doing yoga|yoga", "Meditating",
            "Jogging", "Sprinting", "Marching", "Tiptoeing", "Moonwalking|moonwalk",
            "Dancing ballet|ballet", "Breakdancing", "Slow dancing",
            "Doing the robot|robot dance", "Floss dance|flossing dance",
            "Conducting an orchestra", "Playing air guitar|air guitar",
            "Playing drums", "Playing piano", "Playing violin", "Playing trumpet",
            "Singing opera", "Beatboxing", "Whistling", "Clapping",
            "Taking a selfie", "Texting", "Scrolling on your phone|doomscrolling",
            "Taking a photo", "Recording a video", "Video calling|facetime",
            "Typing on a keyboard|typing", "Writing a letter", "Signing your name",
            "Painting a wall", "Painting a picture", "Drawing", "Knitting",
            "Sewing a button|sewing", "Hammering a nail", "Sawing wood",
            "Drilling a hole", "Screwing in a lightbulb|changing a lightbulb",
            "Mowing the lawn", "Raking leaves", "Watering plants",
            "Planting flowers", "Shoveling snow", "Building a snowman",
            "Making a snow angel", "Throwing a snowball|snowball fight",
            "Fishing", "Casting a fishing line", "Rowing a boat", "Paddling a canoe",
            "Swimming", "Diving", "Doing a cannonball|cannonball",
            "Treading water", "Surfing", "Water skiing", "Riding a bike",
            "Riding a horse", "Riding a motorcycle", "Driving a car",
            "Parallel parking", "Backing up a car|reversing", "Pumping gas",
            "Changing a tire", "Hitchhiking", "Directing traffic",
            "Walking a dog", "Picking up after a dog", "Petting a cat",
            "Feeding a baby", "Rocking a baby", "Changing a diaper",
            "Pushing a stroller", "Giving a piggyback ride|piggyback ride",
            "Climbing a ladder", "Climbing a rope", "Rock climbing",
            "Walking a tightrope|tightrope walking", "Juggling",
            "Doing a cartwheel|cartwheel", "Doing a handstand|handstand",
            "Somersault", "Limbo", "Hula hooping|hula hoop", "Skipping",
            "Hopscotch", "Flying a kite", "Blowing bubbles",
            "Playing hide and seek|hide and seek", "Sneaking around|sneaking",
            "Checking your watch", "Waiting for a bus", "Hailing a taxi",
            "Ordering at a drive-thru", "Grocery shopping", "Pushing a shopping cart",
            "Standing in line", "Winning the lottery", "Proposing|marriage proposal",
            "Getting married", "Slipping on a banana peel", "Walking into a glass door",
            "Stepping on a Lego", "Getting a paper cut", "Burning your hand",
            "Applauding|standing ovation", "Taking a bow", "Saluting",
            "Shrugging", "Facepalm", "Fist bump", "High five", "Thumb wrestling",
            "Arm wrestling", "Playing rock paper scissors|rock paper scissors",
        ],
    },
    "movies": {
        "title": "MOVIES",
        "icon": "🎬",
        "blurb": "Big-screen classics everyone in the room has seen.",
        "difficulty": "medium",
        "items": [
            "Titanic", "Jaws", "Jurassic Park", "King Kong", "Godzilla",
            "The Lion King|lion king", "Frozen", "Moana", "Encanto", "Coco",
            "Toy Story", "Finding Nemo", "Finding Dory", "Monsters Inc|monsters incorporated",
            "The Incredibles|incredibles", "Up", "Ratatouille", "Cars", "Shrek",
            "Kung Fu Panda", "Madagascar", "Ice Age", "Despicable Me",
            "Minions", "The Lego Movie|lego movie", "Aladdin", "The Little Mermaid|little mermaid",
            "Beauty and the Beast", "Cinderella", "Snow White",
            "Sleeping Beauty", "Tangled", "Mulan", "Pocahontas", "Peter Pan",
            "Pinocchio", "Bambi", "Dumbo", "The Jungle Book|jungle book",
            "101 Dalmatians|one hundred one dalmatians|one hundred and one dalmatians|hundred and one dalmatians",
            "Lady and the Tramp", "Mary Poppins", "The Wizard of Oz|wizard of oz",
            "Willy Wonka and the Chocolate Factory|willy wonka|charlie and the chocolate factory",
            "Home Alone", "Elf", "The Grinch|grinch|how the grinch stole christmas",
            "The Polar Express|polar express", "A Christmas Carol|christmas carol",
            "Harry Potter", "The Lord of the Rings|lord of the rings",
            "The Hobbit|hobbit", "Star Wars", "The Empire Strikes Back|empire strikes back",
            "Return of the Jedi", "E.T.|et|e t|extra terrestrial",
            "Back to the Future", "The Terminator|terminator", "The Matrix|matrix",
            "Inception", "Interstellar", "Gravity", "The Martian|martian",
            "Avatar", "Avengers", "Iron Man", "Spider-Man|spiderman",
            "Batman", "The Dark Knight|dark knight", "Superman", "Wonder Woman",
            "Black Panther", "Captain America", "Thor", "Hulk",
            "Guardians of the Galaxy", "Deadpool", "X-Men|xmen",
            "Transformers", "Pirates of the Caribbean", "Indiana Jones",
            "Raiders of the Lost Ark|raiders of the lost ark", "Jumanji",
            "The Mummy|mummy", "Ghostbusters", "Men in Black", "Rocky",
            "Creed", "The Karate Kid|karate kid", "Rush Hour", "Mission Impossible",
            "James Bond|bond|007", "Top Gun", "Fast and Furious|fast and the furious",
            "Mad Max", "John Wick", "Die Hard", "Speed", "Twister",
            "The Fast and the Furious Tokyo Drift|tokyo drift", "Cast Away|castaway",
            "Forrest Gump", "The Truman Show|truman show", "Groundhog Day",
            "Mrs. Doubtfire|mrs doubtfire", "The Mask|mask", "Ace Ventura",
            "Dumb and Dumber", "The Hangover|hangover", "Bridesmaids",
            "Mean Girls", "Clueless", "Legally Blonde", "Grease",
            "Dirty Dancing", "Footloose", "The Sound of Music|sound of music",
            "Singin' in the Rain|singing in the rain|singin in the rain",
            "La La Land", "The Greatest Showman|greatest showman", "Mamma Mia",
            "High School Musical", "Pitch Perfect", "Napoleon Dynamite",
            "The Princess Bride|princess bride", "Hook", "The Goonies|goonies",
            "The Sandlot|sandlot", "Space Jam", "Free Willy", "Babe",
            "Charlotte's Web|charlottes web", "The Parent Trap|parent trap",
            "Matilda", "Paddington", "Night at the Museum",
            "The Chronicles of Narnia|narnia|chronicles of narnia",
            "How to Train Your Dragon", "Big Hero 6|big hero six",
            "Wreck-It Ralph|wreck it ralph", "Zootopia", "Inside Out",
            "Soul", "Luca", "Turning Red", "The Nightmare Before Christmas|nightmare before christmas",
            "Scream", "Halloween", "The Shining|shining", "It|it the movie|pennywise the movie",
            "Psycho", "The Exorcist|exorcist", "A Quiet Place|quiet place",
            "Get Out", "The Sixth Sense|sixth sense", "The Blair Witch Project|blair witch project|blair witch",
        ],
    },
    "characters": {
        "title": "CHARACTERS",
        "icon": "🦸",
        "blurb": "Heroes, villains, and cartoon legends.",
        "difficulty": "medium",
        "items": [
            "Mickey Mouse", "Minnie Mouse", "Donald Duck", "Goofy", "Pluto",
            "Bugs Bunny", "Daffy Duck", "Elmer Fudd", "Tweety Bird|tweety",
            "Road Runner", "Wile E. Coyote|wile e coyote|coyote",
            "Tom and Jerry", "Scooby-Doo|scooby doo", "Shaggy",
            "SpongeBob|spongebob squarepants", "Patrick Star|patrick",
            "Squidward", "Homer Simpson", "Bart Simpson", "Peppa Pig",
            "Bluey", "Dora the Explorer|dora", "Winnie the Pooh|pooh|pooh bear",
            "Tigger", "Eeyore", "Piglet", "Elmo", "Cookie Monster",
            "Big Bird", "Oscar the Grouch", "Kermit the Frog|kermit",
            "Miss Piggy", "Grover", "Bert and Ernie", "Pikachu", "Charizard",
            "Mario", "Luigi", "Princess Peach|peach", "Bowser", "Yoshi",
            "Donkey Kong", "Sonic the Hedgehog|sonic", "Pac-Man|pacman",
            "Kirby", "Link|link from zelda", "Zelda", "Minecraft Steve|steve from minecraft",
            "Creeper|minecraft creeper", "Among Us crewmate|among us",
            "Santa Claus|santa|father christmas", "Mrs. Claus|mrs claus",
            "Rudolph|rudolph the red nosed reindeer", "Frosty the Snowman|frosty",
            "The Easter Bunny|easter bunny", "The Tooth Fairy|tooth fairy",
            "Cupid", "Jack Frost", "The Grim Reaper|grim reaper", "Dracula",
            "Frankenstein|frankensteins monster", "The Mummy (monster)|mummy monster|a mummy",
            "Werewolf", "Zombie", "Vampire", "Ghost", "Witch", "Wizard",
            "Fairy", "Genie", "Leprechaun", "Elf on the Shelf|elf on a shelf",
            "Batman (character)|batman|bruce wayne", "Robin", "The Joker|joker",
            "Harley Quinn", "Catwoman", "Superman (character)|superman|clark kent",
            "Spider-Man (character)|spiderman|spider man|peter parker",
            "Iron Man (character)|iron man|tony stark", "Captain America (character)|captain america",
            "Thor (character)|thor", "Hulk (character)|hulk|the incredible hulk",
            "Black Widow", "Hawkeye", "Thanos", "Loki", "Groot",
            "Rocket Raccoon|rocket", "Wolverine", "Magneto", "Darth Vader",
            "Yoda", "Luke Skywalker", "Princess Leia|leia", "Han Solo",
            "Chewbacca|chewie", "R2-D2|r2d2", "C-3PO|c3po", "BB-8|bb8",
            "Baby Yoda|grogu", "Obi-Wan Kenobi|obi wan|obi wan kenobi",
            "Harry Potter (character)|harry potter", "Hermione Granger|hermione",
            "Ron Weasley|ron", "Dumbledore", "Voldemort", "Hagrid",
            "Dobby", "Gandalf", "Gollum", "Frodo", "Legolas",
            "Elsa", "Anna", "Olaf", "Simba", "Mufasa", "Scar", "Timon",
            "Pumbaa", "Nemo", "Dory", "Buzz Lightyear|buzz", "Woody",
            "Mr. Potato Head|potato head", "Lightning McQueen|mcqueen",
            "Mater", "Shrek (character)|shrek", "Donkey (Shrek)|donkey from shrek",
            "Puss in Boots", "Fiona", "Po (Kung Fu Panda)|po|the dragon warrior",
            "Gru", "A Minion|minion|minions character", "Moana (character)|moana",
            "Maui", "Mirabel", "Ariel", "Ursula", "Sebastian the crab|sebastian",
            "Genie from Aladdin|genie from aladdin", "Jafar", "Jasmine",
            "Belle", "The Beast|beast", "Gaston", "Maleficent",
            "Cruella de Vil|cruella", "Captain Hook", "Tinker Bell|tinkerbell",
            "Mary Poppins (character)|mary poppins", "Willy Wonka (character)|willy wonka",
            "James Bond (character)|james bond|007 character", "Sherlock Holmes",
            "Tarzan", "Hercules", "Robin Hood", "Zorro", "The Lone Ranger|lone ranger",
            "Popeye", "Betty Boop", "Garfield", "Snoopy", "Charlie Brown",
            "Calvin and Hobbes", "Astro Boy", "Goku", "Naruto", "Sailor Moon",
        ],
    },
    "jobs": {
        "title": "JOBS",
        "icon": "👷",
        "blurb": "Occupations with unmistakable moves.",
        "difficulty": "easy",
        "items": [
            "Firefighter", "Police officer", "Doctor", "Nurse", "Surgeon",
            "Dentist", "Eye doctor|optometrist", "Veterinarian|vet",
            "Paramedic", "Pharmacist", "Chiropractor", "Massage therapist",
            "Teacher", "Principal", "Librarian", "Professor", "Scientist",
            "Chemist", "Astronaut", "Pilot", "Flight attendant", "Air traffic controller",
            "Sailor", "Ship captain|captain", "Fisherman", "Lifeguard",
            "Chef", "Baker", "Butcher", "Barista", "Bartender", "Waiter|waitress|server",
            "Pizza delivery driver|pizza delivery", "Food truck owner",
            "Farmer", "Rancher", "Beekeeper", "Gardener", "Landscaper",
            "Lumberjack", "Miner", "Construction worker", "Architect",
            "Engineer", "Electrician", "Plumber", "Carpenter", "Welder",
            "Painter (house)|house painter|painter", "Roofer", "Mechanic",
            "Truck driver", "Bus driver", "Taxi driver", "Train conductor|conductor",
            "Crossing guard", "Mail carrier|mailman|postal worker", "Delivery driver",
            "Garbage collector|trash collector|garbage man", "Janitor|custodian",
            "Window washer", "Chimney sweep", "Locksmith", "Security guard",
            "Detective", "Spy|secret agent", "Judge", "Lawyer", "Accountant",
            "Banker", "Real estate agent|realtor", "Salesperson", "Cashier",
            "Grocery bagger", "Hairdresser|hair stylist", "Barber",
            "Makeup artist", "Nail technician|manicurist", "Tattoo artist",
            "Fashion designer", "Model", "Photographer", "Journalist|reporter",
            "News anchor", "Weather forecaster|weatherman|meteorologist",
            "Radio DJ|dj", "Actor", "Movie director|director", "Stuntman|stunt double",
            "Magician", "Clown", "Juggler (job)|juggler", "Ventriloquist",
            "Puppeteer", "Mime", "Opera singer", "Rock star", "Rapper",
            "Ballerina", "Choreographer", "Orchestra conductor",
            "Boxer", "Wrestler", "Referee", "Coach", "Personal trainer",
            "Yoga instructor", "Ski instructor", "Golf caddy|caddy",
            "Race car driver", "Jockey", "Zookeeper", "Dog groomer",
            "Dog walker", "Animal trainer|lion tamer", "Snake charmer",
            "Fortune teller|psychic", "Auctioneer", "Town crier",
            "King", "Queen", "Knight", "Ninja", "Samurai", "Pirate",
            "Viking", "Cowboy", "Sheriff", "Gold prospector|prospector",
            "Blacksmith", "Monk", "Priest", "President", "Soldier",
            "General", "Drill sergeant", "Paratrooper", "Deep sea diver|scuba diver",
        ],
    },
    "sports": {
        "title": "SPORTS",
        "icon": "🏀",
        "blurb": "Games, moves, and gym-class flashbacks.",
        "difficulty": "easy",
        "items": [
            "Basketball", "Slam dunk", "Free throw", "Dribbling",
            "Football", "Touchdown", "Field goal", "Quarterback",
            "Baseball", "Home run", "Pitching", "Catching a fly ball",
            "Softball", "Soccer", "Penalty kick", "Goalkeeper|goalie",
            "Header (soccer)|header", "Bicycle kick", "Tennis", "Serving in tennis|tennis serve",
            "Ping pong|table tennis", "Badminton", "Volleyball", "Spiking a volleyball|spike",
            "Golf", "Putting|putt", "Mini golf", "Hockey", "Slap shot",
            "Figure skating", "Ice skating", "Speed skating", "Curling",
            "Skiing", "Ski jumping", "Snowboarding", "Sledding", "Bobsled",
            "Luge", "Swimming (sport)|swimming laps|competitive swimming",
            "Backstroke", "Breaststroke", "Butterfly stroke", "High dive|diving board",
            "Synchronized swimming", "Water polo", "Rowing", "Kayaking",
            "Sailing", "Windsurfing", "Wakeboarding", "Jet skiing",
            "Running a marathon|marathon", "Hurdles", "Long jump", "High jump",
            "Pole vault", "Shot put", "Javelin", "Discus", "Relay race",
            "Gymnastics", "Balance beam", "Uneven bars", "Rhythmic gymnastics",
            "Trampoline", "Cheerleading", "Weightlifting", "Bench press",
            "Deadlift", "CrossFit|crossfit", "Bodybuilding|flexing",
            "Boxing", "Kickboxing", "Karate", "Judo", "Taekwondo",
            "Fencing", "Sumo wrestling|sumo", "Arm wrestling (sport)|arm wrestling match",
            "Bowling", "Darts", "Billiards|pool", "Archery", "Skeet shooting",
            "Horseback riding|equestrian", "Rodeo", "Bull riding",
            "Skateboarding", "Ollie", "Rollerblading|inline skating",
            "Roller derby", "BMX|bmx biking", "Mountain biking",
            "Rock climbing (sport)|climbing wall", "Bungee jumping",
            "Skydiving", "Hang gliding", "Parkour", "Zumba",
            "Pilates", "Spin class|spinning", "Treadmill running|treadmill",
            "Frisbee|ultimate frisbee", "Disc golf", "Dodgeball",
            "Kickball", "Tetherball", "Tug of war", "Sack race",
            "Three-legged race|three legged race", "Egg and spoon race",
            "Musical chairs", "Twister (game)|twister", "Foosball",
            "Air hockey", "Cornhole", "Horseshoes", "Bocce ball|bocce",
            "Croquet", "Lacrosse", "Rugby", "Cricket (sport)|cricket game",
            "Polo", "Handball", "Racquetball", "Squash (sport)|squash game",
            "Pickleball", "Surfing (sport)|surfing competition|catching a wave",
            "Fishing tournament|bass fishing", "Log rolling", "Axe throwing",
        ],
    },
    "objects": {
        "title": "OBJECTS",
        "icon": "🪑",
        "blurb": "Stuff around the house — become the thing.",
        "difficulty": "medium",
        "items": [
            "Toothbrush", "Hairbrush", "Comb", "Hair dryer|blow dryer",
            "Mirror", "Towel", "Bathtub", "Toilet", "Plunger", "Soap",
            "Shampoo bottle|shampoo", "Razor", "Toilet paper", "Scale (bathroom)|bathroom scale",
            "Bed", "Pillow", "Blanket", "Alarm clock", "Lamp", "Candle",
            "Flashlight", "Ceiling fan", "Air conditioner", "Heater",
            "Thermostat", "Couch|sofa", "Rocking chair", "Bean bag chair|bean bag",
            "Table", "Desk", "Bookshelf", "Ladder", "Door", "Doorbell",
            "Window", "Curtains", "Key", "Lock", "Mailbox", "Welcome mat|doormat",
            "Refrigerator|fridge", "Freezer", "Oven", "Stove", "Microwave",
            "Toaster", "Blender", "Mixer", "Coffee maker|coffee machine",
            "Kettle|tea kettle", "Dishwasher", "Sink", "Faucet", "Sponge",
            "Frying pan|pan", "Pot", "Spatula", "Whisk", "Rolling pin",
            "Cutting board", "Knife", "Fork", "Spoon", "Chopsticks",
            "Plate", "Bowl", "Cup", "Straw", "Bottle opener", "Corkscrew",
            "Can opener", "Salt shaker", "Pepper grinder|pepper mill",
            "Ice cube tray|ice tray", "Pizza cutter", "Cheese grater",
            "Washing machine", "Dryer", "Iron", "Ironing board",
            "Clothes hanger|hanger", "Clothespin", "Laundry basket",
            "Vacuum cleaner|vacuum", "Broom", "Mop", "Dustpan", "Bucket",
            "Trash can|garbage can", "Recycling bin", "Feather duster|duster",
            "Television|tv", "Remote control|remote", "Radio", "Speaker",
            "Headphones", "Microphone", "Camera", "Tripod", "Telephone|phone",
            "Cell phone|smartphone", "Charger|phone charger", "Laptop",
            "Computer mouse|mouse (computer)", "Keyboard (computer)|computer keyboard",
            "Printer", "Calculator", "Stapler", "Scissors", "Tape dispenser|tape",
            "Glue stick|glue", "Pencil", "Pencil sharpener", "Eraser",
            "Ruler", "Backpack", "Lunchbox", "Notebook", "Envelope",
            "Stamp", "Paperclip", "Rubber band", "Umbrella", "Raincoat",
            "Sunglasses", "Glasses|eyeglasses", "Wallet", "Purse|handbag",
            "Suitcase", "Watch", "Ring", "Necklace", "Earrings", "Crown",
            "Hat", "Scarf", "Gloves", "Mittens", "Boots", "High heels|heels",
            "Flip flops", "Sneakers", "Belt", "Tie|necktie", "Bowtie",
            "Zipper", "Button", "Safety pin", "Piggy bank", "Wallet chain|chain",
            "Guitar", "Piano (object)|piano", "Drum", "Trumpet (object)|trumpet",
            "Harmonica", "Accordion", "Bagpipes", "Violin (object)|violin",
            "Basketball hoop", "Trophy", "Medal", "Whistle", "Stopwatch",
            "Dumbbell", "Yoga mat", "Skateboard", "Bicycle", "Tricycle",
            "Scooter", "Roller skates", "Pogo stick", "Hula hoop (object)|hula hoop toy",
            "Kite", "Balloon", "Teddy bear", "Doll", "Yo-yo|yoyo",
            "Rubik's Cube|rubiks cube", "Jigsaw puzzle|puzzle", "Dice",
            "Playing cards|deck of cards", "Chess board|chessboard",
            "Dartboard", "Telescope", "Binoculars", "Magnifying glass",
            "Compass", "Map", "Globe", "Tent", "Sleeping bag", "Campfire",
            "Fishing rod|fishing pole", "Canteen", "Lantern", "Axe",
            "Hammer", "Screwdriver", "Wrench", "Saw", "Drill", "Toolbox",
            "Nail (tool)|nail", "Shovel", "Rake", "Wheelbarrow", "Hose|garden hose",
            "Lawn mower", "Sprinkler", "Watering can", "Snow globe",
            "Christmas tree", "Wreath", "Stocking", "Jack-o-lantern|jack o lantern|carved pumpkin",
            "Birthday cake", "Pinata|piñata", "Fireworks", "Sparkler",
        ],
    },
    "tv": {
        "title": "TV SHOWS",
        "icon": "📺",
        "blurb": "Series the whole couch knows.",
        "difficulty": "medium",
        "items": [
            "Friends", "The Office|office", "Parks and Recreation|parks and rec",
            "Brooklyn Nine-Nine|brooklyn 99|brooklyn nine nine", "Seinfeld",
            "The Simpsons|simpsons", "Family Guy", "South Park",
            "Rick and Morty", "Futurama", "Bob's Burgers|bobs burgers",
            "Gravity Falls", "Adventure Time", "Avatar The Last Airbender|avatar the last airbender|the last airbender",
            "Teen Titans", "Phineas and Ferb", "Kim Possible",
            "SpongeBob SquarePants (show)|spongebob show", "The Fairly OddParents|fairly oddparents",
            "Rugrats", "Hey Arnold", "Scooby-Doo (show)|scooby doo show",
            "Looney Tunes", "Tom and Jerry (show)|tom and jerry show",
            "Sesame Street", "Mister Rogers|mister rogers neighborhood|mr rogers",
            "Blue's Clues|blues clues", "Paw Patrol", "Bluey (show)|bluey show",
            "Peppa Pig (show)|peppa pig show", "Cocomelon", "Ms. Rachel|ms rachel",
            "Sponge on the Run|spongebob movie", "Stranger Things",
            "Wednesday", "The Mandalorian|mandalorian", "Game of Thrones",
            "House of the Dragon", "The Walking Dead|walking dead",
            "Breaking Bad", "Better Call Saul", "Squid Game",
            "Money Heist", "The Crown|crown", "Bridgerton", "Downton Abbey",
            "Grey's Anatomy|greys anatomy", "House", "ER|er the show",
            "Scrubs", "The Good Doctor|good doctor", "Law and Order",
            "CSI|csi crime scene investigation", "NCIS|ncis",
            "Criminal Minds", "Sherlock (show)|sherlock", "Columbo",
            "MacGyver|macgyver", "The A-Team|a team", "Knight Rider",
            "Baywatch", "Miami Vice", "The X-Files|x files", "Twilight Zone",
            "Black Mirror", "Lost", "Survivor", "The Amazing Race|amazing race",
            "Big Brother", "American Idol", "The Voice|voice",
            "America's Got Talent|americas got talent", "Dancing with the Stars",
            "Wheel of Fortune", "Jeopardy", "The Price is Right|price is right",
            "Family Feud", "Deal or No Deal", "Who Wants to Be a Millionaire|who wants to be a millionaire",
            "Shark Tank", "The Bachelor|bachelor", "Love Island",
            "Keeping Up with the Kardashians|kardashians", "MasterChef|masterchef",
            "Hell's Kitchen|hells kitchen", "The Great British Bake Off|great british bake off|great british baking show",
            "Chopped", "Cake Boss", "Diners Drive-Ins and Dives|diners drive ins and dives|triple d",
            "Mythbusters", "Bill Nye the Science Guy|bill nye",
            "Planet Earth", "Crocodile Hunter|the crocodile hunter",
            "Dora the Explorer (show)|dora show", "Full House",
            "Fresh Prince of Bel-Air|fresh prince|fresh prince of bel air",
            "Saved by the Bell", "Boy Meets World", "Hannah Montana",
            "iCarly|icarly", "Drake and Josh", "Wizards of Waverly Place",
            "That '70s Show|that 70s show|that seventies show", "Cheers",
            "MASH|m a s h", "I Love Lucy", "The Brady Bunch|brady bunch",
            "Gilligan's Island|gilligans island", "Happy Days",
            "The Andy Griffith Show|andy griffith", "Ted Lasso",
            "Only Murders in the Building", "Abbott Elementary",
            "Modern Family", "The Big Bang Theory|big bang theory",
            "How I Met Your Mother", "Two and a Half Men",
            "Everybody Loves Raymond", "King of Queens|the king of queens",
            "Malcolm in the Middle", "Arrested Development",
        ],
    },
    "phrases": {
        "title": "PHRASES",
        "icon": "💬",
        "blurb": "Idioms and sayings — act the words, not the meaning.",
        "difficulty": "hard",
        "items": [
            "Piece of cake", "Break a leg", "Spill the beans", "Hit the hay",
            "Hit the road", "Hit the books", "Under the weather",
            "Over the moon", "Once in a blue moon", "Raining cats and dogs",
            "Hold your horses", "Straight from the horse's mouth|straight from the horses mouth",
            "Don't cry over spilled milk|dont cry over spilled milk|crying over spilled milk",
            "The early bird gets the worm|early bird gets the worm|early bird catches the worm",
            "Kill two birds with one stone", "A bird in the hand|bird in the hand",
            "Let the cat out of the bag", "Curiosity killed the cat",
            "When pigs fly", "Cold turkey", "Goosebumps", "Butterflies in your stomach|butterflies in my stomach",
            "Ants in your pants|ants in my pants", "Cat got your tongue",
            "Elephant in the room", "The lion's share|lions share",
            "Wolf in sheep's clothing|wolf in sheeps clothing",
            "A fish out of water|fish out of water", "Big fish in a small pond",
            "Open a can of worms|can of worms", "Busy as a bee|busy bee",
            "Night owl", "Eager beaver", "Copycat", "Scaredy cat",
            "Couch potato", "Smart cookie", "Tough cookie", "One smart apple|bad apple",
            "The apple of my eye|apple of my eye",
            "An apple a day keeps the doctor away|apple a day",
            "Bread and butter", "Bring home the bacon", "In a pickle",
            "Cool as a cucumber", "Full of beans", "Nutty as a fruitcake|nuts",
            "Sour grapes", "Cherry on top", "Icing on the cake",
            "Have your cake and eat it too|have your cake and eat it",
            "Bite off more than you can chew", "Food for thought",
            "Walking on eggshells", "Egg on your face", "Don't put all your eggs in one basket|all your eggs in one basket",
            "Cry wolf", "Crocodile tears", "Monkey business", "Monkey see monkey do",
            "Get your ducks in a row|ducks in a row", "Like a duck to water",
            "Water under the bridge", "Burn your bridges|burning bridges",
            "Beat around the bush", "Barking up the wrong tree",
            "Out on a limb", "Turn over a new leaf", "Nip it in the bud",
            "Stop and smell the roses", "Every rose has its thorn",
            "Needle in a haystack", "Make hay while the sun shines",
            "Head in the clouds", "On cloud nine", "Every cloud has a silver lining|silver lining",
            "Calm before the storm", "Steal someone's thunder|steal my thunder",
            "Lightning never strikes twice|lightning strikes twice",
            "Snowball effect", "Tip of the iceberg", "Break the ice",
            "Skating on thin ice|on thin ice", "Throw in the towel",
            "Down to the wire", "The ball is in your court|ball is in your court",
            "Drop the ball", "On the ball", "Whole nine yards|the whole nine yards",
            "Out of left field", "Home stretch", "Photo finish",
            "Jump the gun", "Bite the bullet", "Dodge a bullet|dodged a bullet",
            "Shot in the dark", "Long shot", "Big shot", "Call the shots",
            "Burning the midnight oil", "Burn the candle at both ends",
            "Many hands make light work", "All hands on deck",
            "Caught red-handed|caught red handed", "Hands are tied|my hands are tied",
            "Wear your heart on your sleeve|heart on your sleeve",
            "Cross my heart", "Heart of gold", "Cold feet", "Two left feet",
            "Put your foot in your mouth|foot in mouth", "Foot the bill",
            "Off on the wrong foot|start off on the wrong foot",
            "The shoe is on the other foot|shoe on the other foot",
            "Walk a mile in someone's shoes|walk a mile in my shoes",
            "Head over heels", "Achilles' heel|achilles heel",
            "Keep your chin up|chin up", "Stiff upper lip",
            "See eye to eye", "Eye of the storm", "In the blink of an eye|blink of an eye",
            "Turn a blind eye", "Bigger fish to fry", "Off the hook",
            "Hook line and sinker", "Reel it in", "A whale of a time|whale of a time",
            "Loose cannon", "Ship has sailed|that ship has sailed",
            "Rock the boat", "In the same boat", "Miss the boat",
            "Smooth sailing", "Batten down the hatches", "Walk the plank",
            "Bury the hatchet", "Bury your head in the sand|head in the sand",
        ],
    },
    "hard": {
        "title": "IMPOSSIBLE",
        "icon": "🌀",
        "blurb": "Abstract concepts. Good luck acting out 'Monday'.",
        "difficulty": "hard",
        "items": [
            "Gravity", "Time", "Monday", "Friday afternoon", "Déjà vu|deja vu",
            "Jet lag", "Insomnia", "A dream|dream", "A nightmare|nightmare",
            "Memory", "Forgetting something|forgetting", "Nostalgia",
            "The future|future", "The past|past", "Patience", "Boredom",
            "Excitement", "Jealousy", "Embarrassment", "Confidence",
            "Shyness", "Panic", "Relief", "Suspicion", "Curiosity",
            "Wisdom", "Luck", "Karma", "Gossip", "A rumor|rumor",
            "A secret|secret", "The truth|truth", "A white lie|white lie",
            "Sarcasm", "Irony", "A pun|pun", "An inside joke|inside joke",
            "Awkward silence", "Small talk", "Peer pressure",
            "Procrastination", "Multitasking", "Brainstorming",
            "Writer's block|writers block", "A plot twist|plot twist",
            "A cliffhanger|cliffhanger", "Spoilers|a spoiler",
            "Binge watching|binge watch", "Going viral|viral",
            "A meme|meme", "Clickbait", "Wifi going out|no wifi|wifi down",
            "Low battery|phone dying", "Airplane mode", "Buffering",
            "A software update|software update", "A computer virus|computer virus",
            "Spam email|spam", "A password|password", "Autocorrect",
            "A group chat|group chat", "Being left on read|left on read",
            "A bad haircut|bad haircut", "A growth spurt|growth spurt",
            "Puberty", "A midlife crisis|midlife crisis", "Retirement",
            "Taxes|doing taxes", "Inflation", "A traffic jam|traffic jam|traffic",
            "Rush hour", "Road rage", "A speed bump|speed bump",
            "A detour|detour", "Being lost|getting lost", "A shortcut|shortcut",
            "An echo|echo", "A shadow|shadow", "A reflection|reflection",
            "Static electricity|static shock", "Humidity", "A heat wave|heatwave|heat wave",
            "A cold front|cold front", "The wind|wind", "A tornado|tornado",
            "An earthquake|earthquake", "Quicksand", "A mirage|mirage",
            "An eclipse|eclipse", "A black hole|black hole", "Outer space|space",
            "Zero gravity|weightlessness", "Evolution", "Photosynthesis",
            "Hibernation", "Camouflage", "Extinction", "Infinity",
            "A coincidence|coincidence", "An omen|omen", "Superstition",
            "A jinx|jinx", "A curse|curse", "A miracle|miracle",
            "Freedom", "Justice", "Democracy", "Peer review", "Bureaucracy",
            "A loophole|loophole", "Fine print|the fine print",
            "A monopoly (concept)|monopoly concept", "Supply and demand",
            "Minimalism", "Feng shui", "A vibe|vibe|vibes", "An aura|aura",
            "Main character energy", "An awkward hug|awkward hug",
            "A firm handshake|firm handshake", "Personal space",
            "An identity crisis|identity crisis", "Imposter syndrome",
        ],
    },
    "kids": {
        "title": "KIDS",
        "icon": "🧸",
        "blurb": "Easy wins for the youngest actor in the family.",
        "difficulty": "easy",
        "items": [
            "Jumping", "Running", "Hopping", "Skipping (kids)|skipping around",
            "Spinning", "Clapping (kids)|clapping hands", "Waving",
            "Blowing a kiss", "Winking", "Smiling", "Crying", "Laughing",
            "Giggling", "Pouting", "Being angry|angry face", "Being scared|scared",
            "Being surprised|surprised", "Being sleepy|sleepy", "Being hungry|hungry",
            "Eating", "Drinking", "Chewing gum", "Licking a lollipop|lollipop",
            "Eating a cookie", "Drinking milk", "Eating cereal",
            "Brushing hair", "Washing hands", "Taking a bath",
            "Getting a haircut", "Putting on shoes", "Putting on a coat",
            "Zipping a jacket", "Buttoning a shirt", "Waving goodbye",
            "Blowing bubbles (kids)|bubbles", "Playing with blocks|building blocks",
            "Coloring", "Finger painting", "Playing with playdough|playdough",
            "Reading a book", "Telling a story", "Singing", "Humming",
            "Dancing", "Ballet twirl|twirling", "Playing peek-a-boo|peekaboo|peek a boo",
            "Playing patty cake|patty cake", "Ring around the rosie",
            "Duck duck goose", "Tag|playing tag", "Jumping in puddles",
            "Making a mud pie|mud pie", "Catching butterflies",
            "Looking for bugs|finding bugs", "Digging in the sand",
            "Building a sandcastle|sandcastle", "Swinging|on a swing",
            "Going down a slide|slide", "Seesaw", "Climbing a tree",
            "Riding a tricycle (kids)|riding a trike", "Training wheels",
            "Flying like a superhero|superhero flying", "Roaring like a dinosaur|dinosaur roar",
            "Stomping like a giant|giant stomping", "Crawling like a baby|baby crawling",
            "Walking like a penguin|penguin walk", "Hopping like a bunny|bunny hop",
            "Slithering like a snake|snake slither", "Flying like a bird|bird flying",
            "Swimming like a fish|fish swimming", "Galloping like a horse|horse gallop",
            "Waddling like a duck|duck walk", "Prowling like a cat|cat prowl",
            "Howling like a wolf|wolf howl", "Buzzing like a bee|bee buzz",
            "A robot|robot", "A ballerina|ballerina dance", "A cowboy (kids)|cowboy riding",
            "A firefighter (kids)|firefighter spraying", "A police car|police car siren",
            "An airplane|airplane", "A helicopter|helicopter", "A train|choo choo train",
            "A race car|race car", "A rocket ship|rocket|rocket launch",
            "A school bus|school bus", "A boat|boat", "A submarine|submarine",
            "Popcorn popping|popcorn", "A melting ice cream|melting ice cream|ice cream melting",
            "A growing flower|flower growing", "A falling leaf|falling leaves",
            "A twinkling star|twinkle star|twinkling stars", "The sun|sunshine",
            "Rain|raining", "A rainbow|rainbow", "Thunder", "A snowflake|snowflake",
            "Santa's belly laugh|ho ho ho|santa laugh", "Opening presents (kids)|opening christmas presents",
            "Blowing out birthday candles|birthday candles", "A birthday party|birthday",
            "Trick or treating|trick or treat", "Hide and seek (kids)|playing hide and seek",
            "Jump rope (kids)|jumping rope", "Bouncing a ball|bouncing ball",
            "Throwing a ball", "Catching a ball", "Kicking a ball",
            "Rolling down a hill|rolling downhill", "Doing a puzzle",
            "Feeding a pet|feeding the dog", "Walking the dog (kids)|walking a puppy",
            "Tickling", "A bear hug|big hug", "Blowing a raspberry|raspberry",
            "Making a silly face|silly face", "Sticking out your tongue",
            "Crossing your eyes", "Wiggling your ears|ear wiggle",
            "A sneeze coming|about to sneeze", "Hiccups", "Burping",
            "Yawning (kids)|big yawn", "Snoring (kids)|loud snoring",
            "Counting to ten|counting", "The ABCs|abc song|singing the alphabet",
        ],
    },
}

# EVERYTHING = every other deck combined (deduped on NORMALIZED display name,
# so "The Crown" the show and "Crown" the object don't both land in the mix)
_seen = set()
for _slug, _deck in DECKS.items():
    if _slug == "mix":
        continue
    for _item in _deck["items"]:
        _key = norm(_item.split("|", 1)[0])
        if _key not in _seen:
            _seen.add(_key)
            DECKS["mix"]["items"].append(_item)
del _seen


def deck_list():
    """Deck metadata for the lobby picker (no items)."""
    return [{"slug": slug, "title": d["title"], "icon": d["icon"],
             "blurb": d["blurb"], "difficulty": d["difficulty"],
             "count": len(d["items"])}
            for slug, d in DECKS.items()]
